# Agent 02 Trades Ticks Validation

Lanzadera y visor del validador estricto de `trades_ticks`. La semantica es `ACCEPT_ALL_RAW_DIAGNOSE_LATER`.

In [5]:
from pathlib import Path

RUN_ID = 'trades_ticks_prod_2005_2026'
RUN_DIR = Path(r'C:\TSIS_Data\v1\backtest_SmallCaps\runs\polygon_realtime_audit') / RUN_ID
PROBE_ROOT = Path(r'D:\trades_ticks_prod_2005_2026')
SCRIPT = Path(r'C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\202_agent2_validate_trades_ticks_strict.py'
)

print('RUN_DIR:', RUN_DIR)
print('PROBE_ROOT:', PROBE_ROOT)
print('SCRIPT exists:', SCRIPT.exists())

RUN_DIR: C:\TSIS_Data\v1\backtest_SmallCaps\runs\polygon_realtime_audit\trades_ticks_prod_2005_2026
PROBE_ROOT: D:\trades_ticks_prod_2005_2026
SCRIPT exists: True

In [6]:
cmd = f'''python {SCRIPT} --run-id {RUN_ID} --run-dir {RUN_DIR} --probe-root {PROBE_ROOT} --max-files 50000 --sleep-sec 15 --expected-csv {RUN_DIR / "inputs" / "tasks_trades_ticks.csv"}'''
print(cmd)

python C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\202_agent2_validate_trades_ticks_strict.py --run-id trades_ticks_prod_2005_2026 --run-dir C:\TSIS_Data\v1\backtest_SmallCaps\runs\polygon_realtime_audit\trades_ticks_prod_2005_2026 --probe-root D:\trades_ticks_prod_2005_2026 --max-files 50000 --sleep-sec 15 --expected-csv C:\TSIS_Data\v1\backtest_SmallCaps\runs\polygon_realtime_audit\trades_ticks_prod_2005_2026\inputs\tasks_trades_ticks.csv

In [7]:
from pathlib import Path
import json
import pandas as pd

live = RUN_DIR / 'live_status_trades_ticks_strict.json'
cur = RUN_DIR / 'trades_ticks_agent_events_current.csv'
review = RUN_DIR / 'review_queue_trades_ticks_current.csv'
for p in [live, cur, review]:
    print(p.name, p.exists())
if live.exists():
    print(json.dumps(json.loads(live.read_text(encoding='utf-8')), indent=2, ensure_ascii=False))
if cur.exists():
    display(pd.read_csv(cur).head(20).T)
if review.exists():
    display(pd.read_csv(review).head(20).T)

live_status_trades_ticks_strict.json True
trades_ticks_agent_events_current.csv True
review_queue_trades_ticks_current.csv True
{
  "updated_utc": "2026-03-14T12:37:19.582782+00:00",
  "probe_root": "D:\\trades_ticks_prod_2005_2026",
  "max_files": 50000,
  "files_discovered_total": 17639,
  "files_pending": 13581,
  "files_processed_total_state": 17639,
  "files_current_snapshot": 17639,
  "review_queue_pending_files_current": 13581,
  "retry_pending_files_current": 13581,
  "severity_counts_current": {
    "SOFT_FAIL": 13554,
    "PASS": 4058,
    "HARD_FAIL": 27
  },
  "top_causes_current": {
    "duplicates_present_but_under_threshold": 12363,
    "duplicate_excess_ratio_gt_threshold": 1188,
    "duplicate_excess_ratio_gt_hard_cap": 27,
    "rows_lt_10": 3
  },
  "expected_tasks_total": 3068656,
  "expected_tasks_found_current": 17639,
  "expected_tasks_missing_current": 3051017,
  "expected_tasks_empty_current": 8134
}

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
file,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...
processed_at_utc,2026-03-14T12:22:36.468809+00:00,2026-03-14T12:22:36.951403+00:00,2026-03-14T12:22:37.241255+00:00,2026-03-14T12:22:37.587097+00:00,2026-03-14T12:22:37.825740+00:00,2026-03-14T12:22:38.053033+00:00,2026-03-14T12:22:38.375215+00:00,2026-03-14T12:22:38.635015+00:00,2026-03-14T12:22:38.922184+00:00,2026-03-14T12:22:39.202397+00:00,2026-03-14T12:22:39.369165+00:00,2026-03-14T12:22:39.511949+00:00,2026-03-14T12:22:39.773609+00:00,2026-03-14T12:22:39.930992+00:00,2026-03-14T12:22:40.019512+00:00,2026-03-14T12:22:40.126361+00:00,2026-03-14T12:22:40.254118+00:00,2026-03-14T12:22:40.423106+00:00,2026-03-14T12:22:40.514897+00:00,2026-03-14T12:22:40.667601+00:00
ticker,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA
date,2017-06-19,2017-06-20,2017-06-21,2017-06-22,2017-06-23,2017-06-26,2017-06-27,2017-06-28,2017-06-29,2017-06-30,2017-07-03,2017-07-05,2017-07-06,2017-07-07,2017-07-10,2017-07-11,2017-07-12,2017-07-13,2017-07-14,2017-07-17
year,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017
month,6,6,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,7,7,7
session,market,market,market,market,market,market,market,market,market,market,market,market,market,market,market,market,market,market,market,market
rows,137203,84492,86829,63886,60481,98488,70518,68650,75177,44122,33314,60351,36798,20968,24657,32644,40781,22331,28276,50441
missing_required_cols,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
nonpositive_price_rows,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
negative_size_rows,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
duplicate_group_rows,72,103,197,86,36,137,147,144,74,66,34,1785,31,45,58,88,94,22,28,92
duplicate_group_ratio_pct,0.052477,0.121905,0.226883,0.134615,0.059523,0.139103,0.208457,0.20976,0.098434,0.149585,0.102059,2.957697,0.084244,0.214613,0.235227,0.269575,0.230499,0.098518,0.099024,0.182391
duplicate_excess_rows,37,52,101,43,18,71,75,74,37,34,17,979,17,23,30,45,49,12,14,46
duplicate_excess_ratio_pct,0.026967,0.061544,0.116321,0.067307,0.029761,0.07209,0.106356,0.107793,0.049217,0.077059,0.05103,1.622177,0.046198,0.109691,0.121669,0.137851,0.120154,0.053737,0.049512,0.091196
adjacent_exact_repeats,35,51,97,42,17,67,75,73,37,34,17,938,17,21,30,44,48,12,14,45
severity,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL
issues,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]
warns,['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold']
action,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue
task_key,AABA|2017-06-19|market,AABA|2017-06-20|market,AABA|2017-06-21|market,AABA|2017-06-22|market,AABA|2017-06-23|market,AABA|2017-06-26|market,AABA|2017-06-27|market,AABA|2017-06-28|market,AABA|2017-06-29|market,AABA|2017-06-30|market,AABA|2017-07-03|market,AABA|2017-07-05|market,AABA|2017-07-06|market,AABA|2017-07-07|market,AABA|2017-07-10|market,AABA|2017-07-11|market,AABA|2017-07-12|market,AABA|2017-07-13|market,AABA|2017-07-14|market,AABA|2017-07-17|market

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
file,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...,D:\trades_ticks_prod_2005_2026\AABA\year=2017\...
processed_at_utc,2026-03-14T12:22:36.468809+00:00,2026-03-14T12:22:36.951403+00:00,2026-03-14T12:22:37.241255+00:00,2026-03-14T12:22:37.587097+00:00,2026-03-14T12:22:37.825740+00:00,2026-03-14T12:22:38.053033+00:00,2026-03-14T12:22:38.375215+00:00,2026-03-14T12:22:38.635015+00:00,2026-03-14T12:22:38.922184+00:00,2026-03-14T12:22:39.202397+00:00,2026-03-14T12:22:39.369165+00:00,2026-03-14T12:22:39.511949+00:00,2026-03-14T12:22:39.773609+00:00,2026-03-14T12:22:39.930992+00:00,2026-03-14T12:22:40.019512+00:00,2026-03-14T12:22:40.126361+00:00,2026-03-14T12:22:40.254118+00:00,2026-03-14T12:22:40.423106+00:00,2026-03-14T12:22:40.514897+00:00,2026-03-14T12:22:40.667601+00:00
ticker,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA,AABA
date,2017-06-19,2017-06-20,2017-06-21,2017-06-22,2017-06-23,2017-06-26,2017-06-27,2017-06-28,2017-06-29,2017-06-30,2017-07-03,2017-07-05,2017-07-06,2017-07-07,2017-07-10,2017-07-11,2017-07-12,2017-07-13,2017-07-14,2017-07-17
year,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017
month,6,6,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,7,7,7
session,market,market,market,market,market,market,market,market,market,market,market,market,market,market,market,market,market,market,market,market
rows,137203,84492,86829,63886,60481,98488,70518,68650,75177,44122,33314,60351,36798,20968,24657,32644,40781,22331,28276,50441
missing_required_cols,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
nonpositive_price_rows,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
negative_size_rows,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
duplicate_group_rows,72,103,197,86,36,137,147,144,74,66,34,1785,31,45,58,88,94,22,28,92
duplicate_group_ratio_pct,0.052477,0.121905,0.226883,0.134615,0.059523,0.139103,0.208457,0.20976,0.098434,0.149585,0.102059,2.957697,0.084244,0.214613,0.235227,0.269575,0.230499,0.098518,0.099024,0.182391
duplicate_excess_rows,37,52,101,43,18,71,75,74,37,34,17,979,17,23,30,45,49,12,14,46
duplicate_excess_ratio_pct,0.026967,0.061544,0.116321,0.067307,0.029761,0.07209,0.106356,0.107793,0.049217,0.077059,0.05103,1.622177,0.046198,0.109691,0.121669,0.137851,0.120154,0.053737,0.049512,0.091196
adjacent_exact_repeats,35,51,97,42,17,67,75,73,37,34,17,938,17,21,30,44,48,12,14,45
severity,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL,SOFT_FAIL
issues,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]
warns,['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold'],['duplicates_present_but_under_threshold']
action,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue,review_queue
task_key,AABA|2017-06-19|market,AABA|2017-06-20|market,AABA|2017-06-21|market,AABA|2017-06-22|market,AABA|2017-06-23|market,AABA|2017-06-26|market,AABA|2017-06-27|market,AABA|2017-06-28|market,AABA|2017-06-29|market,AABA|2017-06-30|market,AABA|2017-07-03|market,AABA|2017-07-05|market,AABA|2017-07-06|market,AABA|2017-07-07|market,AABA|2017-07-10|market,AABA|2017-07-11|market,AABA|2017-07-12|market,AABA|2017-07-13|market,AABA|2017-07-14|market,AABA|2017-07-17|market

In [8]:


from pathlib import Path

root = Path(r"D:\trades_ticks_preprod10x5")
files = sorted(root.glob("*/*/*/*/market.parquet"))

print("market.parquet files:", len(files))
for p in files[:30]:
    print(p)

market.parquet files: 0