

`download_reference_universe_polygon.py`

Qué descarga:

```
- GET /v3/reference/tickers/{ticker} -> overview
- GET /vX/reference/tickers/{ticker}/events -> events
- GET /v3/reference/splits?ticker=... -> splits
- GET /v3/reference/dividends?ticker=... -> dividends
- GET /v3/reference/tickers/types -> ticker_types
- GET /v3/reference/exchanges -> exchanges
- GET /v3/reference/tickers -> all_tickers por fechas de corte
```

Input por defecto:

- `tickers_2005_2026_upper.parquet`

El overview usa por defecto:

- `date = snapshot_date` del input si existe

El all_tickers usa por defecto:

- `unique_input_snapshot_dates`

Outputs:



```
- D:\reference\overview\ticker=...
- D:\reference\events\ticker=...
- D:\reference\splits\ticker=...
- D:\reference\dividends\ticker=...
- D:\reference\ticker_types\ticker_types.parquet
- D:\reference\exchanges\exchanges.parquet
- D:\reference\all_tickers\snapshot_date=....parquet
- progreso y auditoría en:
    - D:\reference\_run\download_reference_universe_polygon.progress.json
    - D:\reference\_run\download_reference_universe_polygon.audit.csv
    - D:\reference\_run\download_reference_universe_polygon.errors.csv
```

Lanzadera corta desde terminal:

```
& "C:\TSIS_Data\v1\backtest_SmallCaps\backtest\Scripts\python.exe" C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\download_reference_universe_polygon.py --input C:\TSIS_Data\v1\backtest_SmallCaps\data\reference\universe_pti\tickers_2005_2026_upper.parquet --outdir D:\reference --datasets overview,events,splits,dividends,ticker_types,exchanges,all_tickers --workers 8 --batch-size 200 --max-pages 100000 --resume --resume-validate --active-filter all --overview-date-mode snapshot_date --all-tickers-date-mode unique_input_snapshot_dates
```

Si quieres empezar con una smoke:

```
& "C:\TSIS_Data\v1\backtest_SmallCaps\backtest\Scripts\python.exe" C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\download_reference_universe_polygon.py --input C:\TSIS_Data\v1\backtest_SmallCaps\data\reference\universe_pti\tickers_2005_2026_upper.parquet --outdir D:\reference --datasets overview,events,splits,dividends,ticker_types,exchanges,all_tickers --workers 4 --batch-size 50 --max-rows 25 --max-cuts 10 --resume --resume-validate

```

Punto importante:

- esto descarga la capa Reference / Universe
- no construye todavía el PTI final
- deja la materia prima local para luego auditar y reconstruir el PTI sin volver a pegarle a Polygon

In [1]:
from pathlib import Path

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\audit_reference_universe_polygon.py")

REFERENCE_ROOT = Path(r"D:\reference")
TOP_N = 30
SHOW_HEAD_TAIL = True

exec(SCRIPT.read_text(encoding="utf-8"), globals(), globals())

=== PATHS USADOS ===
REFERENCE_ROOT: D:\reference
RUN_DIR: D:\reference\_run
AUDIT_CSV: D:\reference\_run\download_reference_universe_polygon.audit.csv
ERRORS_CSV: D:\reference\_run\download_reference_universe_polygon.errors.csv
PROGRESS_JSON: D:\reference\_run\download_reference_universe_polygon.progress.json

=== PROGRESS ===
{
  "status": "completed",
  "input": "C:\\TSIS_Data\\v1\\backtest_SmallCaps\\data\\reference\\universe_pti\\tickers_2005_2026_upper.parquet",
  "outdir": "D:\\reference",
  "datasets": [
    "overview",
    "events",
    "splits",
    "dividends",
    "ticker_types",
    "exchanges",
    "all_tickers"
  ],
  "done_tickers": 12468,
  "total_tickers": 12468,
  "progress_pct": 100.0,
  "errors": 200,
  "updated_at_utc": "2026-03-11T17:27:33.546905+00:00",
  "audit_csv": "D:\\reference\\_run\\download_reference_universe_polygon.audit.csv",
  "errors_csv": "D:\\reference\\_run\\download_reference_universe_polygon.errors.csv"
}

KeyboardInterrupt:

In [ ]:
from pathlib import Path

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\audit_reference_overview_404.py")

REFERENCE_ROOT = Path(r"D:\reference")
UNIVERSE_PATH = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\data\reference\universe_pti\tickers_2005_2026.parquet")
TOP_N = 50

exec(SCRIPT.read_text(encoding="utf-8"), globals(), globals())

=== OVERVIEW 404 COUNT ===
217

=== FLAGS ===

             flag  count
0      endswith_w    210
1     endswith_ws      0
2      endswith_u      0
3      endswith_r      1
4    contains_dot      7
5  contains_slash      0
6     in_universe    217

=== BY STATUS ===

  universe_status  count
0        inactive    216
1          active      1

=== BY EXCHANGE ===

  universe_primary_exchange  count
0                      XNYS    210
1                      XASE      6
2                      XNAS      1

=== TOP SAMPLE ===

,ticker,request_date,universe_status,universe_primary_exchange,universe_first_seen_date,universe_last_seen_date,universe_entity_id,universe_name,endswith_w,endswith_ws,endswith_u,endswith_r,contains_dot,contains_slash
0,ABHW,2010-12-19,inactive,XNYS,2010-12-13,2010-12-19,ABHw|XNYS,ABITIBIBOWATER INC COM STK NEW (DE)W.I.,True,False,False,False,False,False
1,ABTW,2013-01-01,inactive,XNYS,2012-12-11,2013-01-01,ABTw|XNYS,ABBOTT LABORATORIES COM STK (IL) EX-DIST W.I.,True,False,False,False,False,False
2,ACTW,2014-07-01,inactive,XNYS,2014-07-01,2014-07-01,ACTw|XNYS,ACTAVIS PLC COM SHS (IRL)W.I.,True,False,False,False,False,False
3,ACVW,2006-11-16,inactive,XNYS,2006-11-13,2006-11-16,ACVw|XNYS,ALBERTO CULVER CO NEW W.I,True,False,False,False,False,False
4,ADNTW,2016-10-31,inactive,XNYS,2016-10-19,2016-10-31,ADNTw|XNYS,Adient plc,True,False,False,False,False,False
5,ADSW,2021-11-07,inactive,XNYS,2021-11-01,2021-11-07,ADSw|XNYS,Alliance Data Systems Corporation,True,False,False,False,False,False
6,ADSW,2021-11-07,inactive,XNYS,2019-09-24,2019-09-24,BBG003FJ1CY0,"Advanced Disposal Services, Inc.",True,False,False,False,False,False
7,ADSW,2021-11-07,inactive,XNYS,2016-10-10,2020-11-01,BBG00DZS7S66,"Advanced Disposal Services, Inc.",True,False,False,False,False,False
8,ADTW,2012-09-30,inactive,XNYS,2012-09-18,2012-09-30,ADTw|XNYS,ADT CORP W.I.,True,False,False,False,False,False
9,AHLP,2005-12-14,inactive,XNYS,2005-12-14,2005-12-14,AHLp|XNYS,ASPEN INS HLDGS LTD PERP PFD INCM EQTY REPL SE...,False,False,False,False,False,False
10,AHOW,2007-08-28,inactive,XNYS,2007-08-23,2007-08-28,AHOw|XNYS,KONINKLIJKE AHOLD NV SPONSORED ADR 2007 W.I.,True,False,False,False,False,False
11,AHPW,2013-11-19,inactive,XNYS,2013-11-08,2013-11-19,AHPw|XNYS,ASHFORD HOSPITALITY PRIME INC COM SK (MD) W.I.,True,False,False,False,False,False
12,AIVW,2020-12-14,inactive,XNYS,2020-12-03,2020-12-14,AIVw|XNYS,Apartment Investment and Management Company,True,False,False,False,False,False
13,ALCW,2006-11-09,inactive,XNYS,2006-10-26,2006-11-09,ALCw|XNYS,ASSISTED LIVING CONCEPTS INC NEV NEW W.I.,True,False,False,False,False,False
14,ALLEW,2013-12-02,inactive,XNYS,2013-11-20,2013-12-02,ALLEw|XNYS,ALLEGION PUB LTD CO W.I. (IRL),True,False,False,False,False,False
15,ALVW,2018-07-01,inactive,XNYS,2018-06-11,2018-07-01,ALVw|XNYS,"Autoliv, Inc.",True,False,False,False,False,False
16,AMFWW,2014-11-24,inactive,XNYS,2014-11-17,2014-11-24,AMFWw|XNYS,AMEC FORSTER WHEELER PLC ADS,True,False,False,False,False,False
17,AOLW,2009-12-09,inactive,XNYS,2009-11-25,2009-12-09,AOLw|XNYS,AOL INC COMMON STOCK WI,True,False,False,False,False,False
18,APTVW,2017-12-04,inactive,XNYS,2017-11-21,2017-12-04,APTVw|XNYS,Aptiv PLC,True,False,False,False,False,False
19,ARMKW,2023-10-01,inactive,XNYS,2023-09-27,2023-10-01,BBG01JFXHPX8,Aramark,True,False,False,False,False,False
20,ARPW,2012-03-13,inactive,XNYS,2012-02-27,2012-03-13,ARPw|XNYS,ATLAS RES PARTNERS L P COM UIT REPSTG LTD PTNR...,True,False,False,False,False,False
21,ASHW,2017-05-14,inactive,XNYS,2017-05-03,2017-05-14,ASHw|XNYS,Ashland Global Holdings Inc.,True,False,False,False,False,False
22,ASXW,2018-05-01,inactive,XNYS,2018-04-18,2018-05-01,BBG00KLHL9W6,"ASE Industrial Holding Co., Ltd.",True,False,False,False,False,False
23,AXLLW,2013-02-04,inactive,XNYS,2013-01-30,2013-02-04,AXLLw|XNYS,AXIALL CORP COM STK (DE) W.I.,True,False,False,False,False,False
24,BBUW,2022-03-14,inactive,XNYS,2016-06-02,2022-03-14,BBUw|XNYS,Brookfield Business Partners L.P. Limited Part...,True,False,False,False,False,False
25,BDXW,2022-03-31,inactive,XNYS,2022-03-23,2022-03-31,BDXw|XNYS,"Becton, Dickinson and Company",True,False,False,False,False,False
26,BEPW,2020-07-29,inactive,XNYS,2020-07-24,2020-07-29,BEPw|XNYS,Brookfield Renewable Partners L.P. Limited Par...,True,False,False,False,False,False
27,BHVNW,2022-10-04,inactive,XNYS,2022-09-23,2022-10-04,BHVNw|XNYS,Biohaven Ltd.,True,False,False,False,False,False
28,BIPW,2020-03-30,inactive,XNYS,2008-01-10,2020-03-30,BIPw|XNYS,Brookfield Infrastructure Partners L.P. Limite...,True,False,False,False,False,False
29,BNKW,2006-02-09,inactive,XNYS,2006-02-03,2006-02-09,BNKw|XNYS,TD BANKNORTH INC. W.I.,True,False,False,False,False,False
30,BNW,2022-12-12,inactive,XNYS,2022-12-01,2022-12-12,BBG01BPHP412,Brookfield Corporation,True,False,False,False,False,False
31,BPYW,2013-04-14,inactive,XNYS,2013-03-25,2013-04-14,BPYw|XNYS,BROOKFIELD PPTY PARTNERS L P UIT LTD PARTNERSH...,True,False,False,False,False,False
32,BTXW,2016-01-03,inactive,XASE,2015-12-31,2016-01-03,BTXw|XASE,BIOTIME INC EX-DISTRIBUTION WI,True,False,False,False,False,False
33,BWAW,2023-07-04,inactive,XNYS,2023-06-28,2023-07-04,BBG01H0F86K3,BorgWarner Inc.,True,False,False,False,False,False
34,BWCW,2010-08-01,inactive,XNYS,2010-07-13,2010-08-01,BWCw|XNYS,BABCOCK & WILCOX COMPANY COM STK W.I.,True,False,False,False,False,False
35,BXLTW,2015-06-30,inactive,XNYS,2015-06-17,2015-06-30,BXLTw|XNYS,BAXALTA INC COM STK (DE) W.I.,True,False,False,False,False,False
36,CAGW,2016-11-09,inactive,XNYS,2016-10-31,2016-11-09,CAGw|XNYS,"ConAgra Foods, Inc.",True,False,False,False,False,False
37,CBSOW,2014-07-16,inactive,XNYS,2014-07-08,2014-07-16,CBSOw|XNYS,CBS OUTDOOR AMERS INC COM STK (MD)W.I.,True,False,False,False,False,False
38,CCPW,2015-08-17,inactive,XNYS,2015-08-14,2015-08-17,CCPw|XNYS,"CARE CAPITAL PROPERTIES, INC COM W.I.",True,False,False,False,False,False
39,CFLW,2008-11-02,inactive,XNYS,2008-10-20,2008-11-02,CFLw|XNYS,"BRINK'S HOME SECURITY HOLDINGS, INC. WI",True,False,False,False,False,False
40,CFNW,2009-08-31,inactive,XNYS,2009-08-24,2009-08-31,CFNw|XNYS,CAREFUSION CORPORATION W.I.,True,False,False,False,False,False
41,CHTW,2010-02-10,inactive,XNYS,2007-12-20,2010-02-10,CHTw|XNYS,CHUNGHWA TELECOM CO LTD SPONSORED ADR NEW 2010...,True,False,False,False,False,False
42,CKHW,2017-06-01,inactive,XNYS,2017-05-18,2017-06-01,CKHw|XNYS,SEACOR Holdings Inc.,True,False,False,False,False,False
43,CLNSPF,2017-01-17,inactive,XNYS,2017-01-13,2017-01-17,CLNSpF|XNYS,"Colony NorthStar, Inc.",False,False,False,False,False,False
44,CMDBW,2025-05-07,inactive,XNYS,2025-05-01,2025-05-07,CMDBw|XNYS,Costamare Bulkers Holdings Limited,True,False,False,False,False,False
45,CMG.BW,2006-10-12,inactive,XNYS,2006-10-06,2006-10-12,CMG.Bw|XNYS,"CHIPOTLE MEXICAN GRILL, INC. CLASS B COMMON ST...",True,False,False,False,True,False
46,CMREW,2025-05-06,inactive,XNYS,2025-05-01,2025-05-06,CMREw|XNYS,Costamare Inc.,True,False,False,False,False,False
47,COVW,2007-07-01,inactive,XNYS,2007-06-14,2007-07-01,COVw|XNYS,"COVIDIEN LTD, COM WI",True,False,False,False,False,False
48,CPGXW,2015-07-01,inactive,XNYS,2015-06-19,2015-07-01,CPGXw|XNYS,COLUMBIA PIPELINE GROUP IN COM STK W.I. (DE),True,False,False,False,False,False
49,CPLGW,2018-05-30,inactive,XNYS,2018-05-17,2018-05-30,CPLGw|XNYS,CorePoint Lodging Inc.,True,False,False,False,False,False

In [ ]:
from pathlib import Path
import json
import pandas as pd

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\build_tickers_2005_2026_upper_clean.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals(), globals())

summary = json.loads(Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\data\reference\universe_pti\tickers_2005_2026_upper_clean.summary.json").read_text(encoding="utf-8"))
excluded = pd.read_parquet(r"C:\TSIS_Data\v1\backtest_SmallCaps\data\reference\universe_pti\tickers_2005_2026_upper_excluded_overview404.parquet")
remap = pd.read_parquet(r"C:\TSIS_Data\v1\backtest_SmallCaps\data\reference\universe_pti\tickers_2005_2026_upper_remap_candidates.parquet")
clean = pd.read_parquet(r"C:\TSIS_Data\v1\backtest_SmallCaps\data\reference\universe_pti\tickers_2005_2026_upper_clean.parquet")

print(json.dumps(summary, indent=2, ensure_ascii=False))
display(excluded.head(20))
display(remap.head(20))
display(clean.head(5))
display(clean.tail(5))

tickers_2005_2026_upper_clean build completed
CLEAN_PARQUET: C:\TSIS_Data\v1\backtest_SmallCaps\data\reference\universe_pti\tickers_2005_2026_upper_clean.parquet
EXCLUDED_PARQUET: C:\TSIS_Data\v1\backtest_SmallCaps\data\reference\universe_pti\tickers_2005_2026_upper_excluded_overview404.parquet
REMAP_CANDIDATES_PARQUET: C:\TSIS_Data\v1\backtest_SmallCaps\data\reference\universe_pti\tickers_2005_2026_upper_remap_candidates.parquet
SUMMARY_JSON: C:\TSIS_Data\v1\backtest_SmallCaps\data\reference\universe_pti\tickers_2005_2026_upper_clean.summary.json
excluded_rows: 200
clean_rows: 12268
remap_candidate_rows: 193
{
  "universe_full_rows": 15979,
  "universe_upper_rows": 12468,
  "overview_404_unique_tickers": 200,
  "excluded_rows": 200,
  "clean_rows": 12268,
  "remap_candidate_rows": 193,
  "paths": {
    "universe_full": "C:\\TSIS_Data\\v1\\backtest_SmallCaps\\data\\reference\\universe_pti\\tickers_2005_2026.parquet",
    "universe_upper": "C:\\TSIS_Data\\v1\\backtest_SmallCaps\\data\\reference\\universe_pti\\tickers_2005_2026_upper.parquet",
    "audit_csv": "D:\\reference\\_run\\download_reference_universe_polygon.audit.csv",
    "clean_parquet": "C:\\TSIS_Data\\v1\\backtest_SmallCaps\\data\\reference\\universe_pti\\tickers_2005_2026_upper_clean.parquet",
    "excluded_parquet": "C:\\TSIS_Data\\v1\\backtest_SmallCaps\\data\\reference\\universe_pti\\tickers_2005_2026_upper_excluded_overview404.parquet",
    "remap_candidates_parquet": "C:\\TSIS_Data\\v1\\backtest_SmallCaps\\data\\reference\\universe_pti\\tickers_2005_2026_upper_remap_candidates.parquet"
  }
}

,ticker,name,market,locale,primary_exchange,type,active,currency_name,cik,composite_figi,...,latest_active,status_confidence,status,request_date,msg,out_file,suggested_base_ticker,suggested_base_exists_in_upper,exclude_reason,full_name
0,ABHW,ABITIBIBOWATER INC COM STK NEW (DE)W.I.,stocks,us,XNYS,CS,True,usd,0001468079,NaN,...,True,high,inactive,2010-12-19,http_404,D:\reference\overview\ticker=ABHW\overview_ABH...,ABH,True,overview_404,ABITIBIBOWATER INC COM STK NEW (DE)W.I.
1,ABTW,ABBOTT LABORATORIES COM STK (IL) EX-DIST W.I.,stocks,us,XNYS,CS,True,usd,0000001800,NaN,...,True,high,inactive,2013-01-01,http_404,D:\reference\overview\ticker=ABTW\overview_ABT...,ABT,True,overview_404,ABBOTT LABORATORIES COM STK (IL) EX-DIST W.I.
2,ACTW,ACTAVIS PLC COM SHS (IRL)W.I.,stocks,us,XNYS,CS,True,usd,0000884629,NaN,...,True,high,inactive,2014-07-01,http_404,D:\reference\overview\ticker=ACTW\overview_ACT...,ACT,True,overview_404,ACTAVIS PLC COM SHS (IRL)W.I.
3,ACVW,ALBERTO CULVER CO NEW W.I,stocks,us,XNYS,CS,True,usd,0000003327,NaN,...,True,high,inactive,2006-11-16,http_404,D:\reference\overview\ticker=ACVW\overview_ACV...,ACV,True,overview_404,ALBERTO CULVER CO NEW W.I
4,ADNTW,Adient plc,stocks,us,XNYS,CS,True,usd,0001670541,NaN,...,True,high,inactive,2016-10-31,http_404,D:\reference\overview\ticker=ADNTW\overview_AD...,ADNT,True,overview_404,Adient plc
5,ADSW,Alliance Data Systems Corporation,stocks,us,XNYS,CS,True,usd,0001101215,NaN,...,True,high,inactive,2021-11-07,http_404,D:\reference\overview\ticker=ADSW\overview_ADS...,ADS,False,overview_404,Alliance Data Systems Corporation
6,ADTW,ADT CORP W.I.,stocks,us,XNYS,CS,True,usd,0001546640,NaN,...,True,high,inactive,2012-09-30,http_404,D:\reference\overview\ticker=ADTW\overview_ADT...,ADT,True,overview_404,ADT CORP W.I.
7,AHLP,ASPEN INS HLDGS LTD PERP PFD INCM EQTY REPL SE...,stocks,us,XNYS,CS,True,usd,0001267395,NaN,...,True,high,inactive,2005-12-14,http_404,D:\reference\overview\ticker=AHLP\overview_AHL...,AHL,True,overview_404,ASPEN INS HLDGS LTD PERP PFD INCM EQTY REPL SE...
8,AHOW,KONINKLIJKE AHOLD NV SPONSORED ADR 2007 W.I.,stocks,us,XNYS,CS,True,usd,0000854499,NaN,...,True,high,inactive,2007-08-28,http_404,D:\reference\overview\ticker=AHOW\overview_AHO...,AHO,True,overview_404,KONINKLIJKE AHOLD NV SPONSORED ADR 2007 W.I.
9,AHPW,ASHFORD HOSPITALITY PRIME INC COM SK (MD) W.I.,stocks,us,XNYS,CS,True,usd,0001574085,NaN,...,True,high,inactive,2013-11-19,http_404,D:\reference\overview\ticker=AHPW\overview_AHP...,AHP,True,overview_404,ASHFORD HOSPITALITY PRIME INC COM SK (MD) W.I.
10,AIVW,Apartment Investment and Management Company,stocks,us,XNYS,CS,True,usd,0000922864,NaN,...,True,high,inactive,2020-12-14,http_404,D:\reference\overview\ticker=AIVW\overview_AIV...,AIV,True,overview_404,Apartment Investment and Management Company
11,ALCW,ASSISTED LIVING CONCEPTS INC NEV NEW W.I.,stocks,us,XNYS,CS,True,usd,0000929994,NaN,...,True,high,inactive,2006-11-09,http_404,D:\reference\overview\ticker=ALCW\overview_ALC...,ALC,True,overview_404,ASSISTED LIVING CONCEPTS INC NEV NEW W.I.
12,ALLEW,ALLEGION PUB LTD CO W.I. (IRL),stocks,us,XNYS,CS,True,usd,0001579241,NaN,...,True,high,inactive,2013-12-02,http_404,D:\reference\overview\ticker=ALLEW\overview_AL...,ALLE,True,overview_404,ALLEGION PUB LTD CO W.I. (IRL)
13,ALVW,"Autoliv, Inc.",stocks,us,XNYS,CS,True,usd,0001034670,NaN,...,True,high,inactive,2018-07-01,http_404,D:\reference\overview\ticker=ALVW\overview_ALV...,ALV,True,overview_404,"Autoliv, Inc."
14,AMFWW,AMEC FORSTER WHEELER PLC ADS,stocks,us,XNYS,CS,True,usd,NaN,NaN,...,True,high,inactive,2014-11-24,http_404,D:\reference\overview\ticker=AMFWW\overview_AM...,AMFW,True,overview_404,AMEC FORSTER WHEELER PLC ADS
15,AOLW,AOL INC COMMON STOCK WI,stocks,us,XNYS,CS,True,usd,0001468516,NaN,...,True,high,inactive,2009-12-09,http_404,D:\reference\overview\ticker=AOLW\overview_AOL...,AOL,True,overview_404,AOL INC COMMON STOCK WI
16,APTVW,Aptiv PLC,stocks,us,XNYS,CS,True,usd,0001521332,NaN,...,True,high,inactive,2017-12-04,http_404,D:\reference\overview\ticker=APTVW\overview_AP...,APTV,True,overview_404,Aptiv PLC
17,ARMKW,Aramark,stocks,us,XNYS,CS,True,usd,0001584509,BBG01JFXHPX8,...,True,high,inactive,2023-10-01,http_404,D:\reference\overview\ticker=ARMKW\overview_AR...,ARMK,True,overview_404,Aramark
18,ARPW,ATLAS RES PARTNERS L P COM UIT REPSTG LTD PTNR...,stocks,us,XNYS,CS,True,usd,0001532750,NaN,...,True,high,inactive,2012-03-13,http_404,D:\reference\overview\ticker=ARPW\overview_ARP...,ARP,True,overview_404,ATLAS RES PARTNERS L P COM UIT REPSTG LTD PTNR...
19,ASHW,Ashland Global Holdings Inc.,stocks,us,XNYS,CS,True,usd,0001674862,NaN,...,True,high,inactive,2017-05-14,http_404,D:\reference\overview\ticker=ASHW\overview_ASH...,ASH,True,overview_404,Ashland Global Holdings Inc.

,ticker,name,market,locale,primary_exchange,type,active,currency_name,cik,composite_figi,...,latest_active,status_confidence,status,request_date,msg,out_file,suggested_base_ticker,suggested_base_exists_in_upper,exclude_reason,full_name
0,ABHW,ABITIBIBOWATER INC COM STK NEW (DE)W.I.,stocks,us,XNYS,CS,True,usd,0001468079,NaN,...,True,high,inactive,2010-12-19,http_404,D:\reference\overview\ticker=ABHW\overview_ABH...,ABH,True,overview_404,ABITIBIBOWATER INC COM STK NEW (DE)W.I.
1,ABTW,ABBOTT LABORATORIES COM STK (IL) EX-DIST W.I.,stocks,us,XNYS,CS,True,usd,0000001800,NaN,...,True,high,inactive,2013-01-01,http_404,D:\reference\overview\ticker=ABTW\overview_ABT...,ABT,True,overview_404,ABBOTT LABORATORIES COM STK (IL) EX-DIST W.I.
2,ACTW,ACTAVIS PLC COM SHS (IRL)W.I.,stocks,us,XNYS,CS,True,usd,0000884629,NaN,...,True,high,inactive,2014-07-01,http_404,D:\reference\overview\ticker=ACTW\overview_ACT...,ACT,True,overview_404,ACTAVIS PLC COM SHS (IRL)W.I.
3,ACVW,ALBERTO CULVER CO NEW W.I,stocks,us,XNYS,CS,True,usd,0000003327,NaN,...,True,high,inactive,2006-11-16,http_404,D:\reference\overview\ticker=ACVW\overview_ACV...,ACV,True,overview_404,ALBERTO CULVER CO NEW W.I
4,ADNTW,Adient plc,stocks,us,XNYS,CS,True,usd,0001670541,NaN,...,True,high,inactive,2016-10-31,http_404,D:\reference\overview\ticker=ADNTW\overview_AD...,ADNT,True,overview_404,Adient plc
5,ADTW,ADT CORP W.I.,stocks,us,XNYS,CS,True,usd,0001546640,NaN,...,True,high,inactive,2012-09-30,http_404,D:\reference\overview\ticker=ADTW\overview_ADT...,ADT,True,overview_404,ADT CORP W.I.
6,AHLP,ASPEN INS HLDGS LTD PERP PFD INCM EQTY REPL SE...,stocks,us,XNYS,CS,True,usd,0001267395,NaN,...,True,high,inactive,2005-12-14,http_404,D:\reference\overview\ticker=AHLP\overview_AHL...,AHL,True,overview_404,ASPEN INS HLDGS LTD PERP PFD INCM EQTY REPL SE...
7,AHOW,KONINKLIJKE AHOLD NV SPONSORED ADR 2007 W.I.,stocks,us,XNYS,CS,True,usd,0000854499,NaN,...,True,high,inactive,2007-08-28,http_404,D:\reference\overview\ticker=AHOW\overview_AHO...,AHO,True,overview_404,KONINKLIJKE AHOLD NV SPONSORED ADR 2007 W.I.
8,AHPW,ASHFORD HOSPITALITY PRIME INC COM SK (MD) W.I.,stocks,us,XNYS,CS,True,usd,0001574085,NaN,...,True,high,inactive,2013-11-19,http_404,D:\reference\overview\ticker=AHPW\overview_AHP...,AHP,True,overview_404,ASHFORD HOSPITALITY PRIME INC COM SK (MD) W.I.
9,AIVW,Apartment Investment and Management Company,stocks,us,XNYS,CS,True,usd,0000922864,NaN,...,True,high,inactive,2020-12-14,http_404,D:\reference\overview\ticker=AIVW\overview_AIV...,AIV,True,overview_404,Apartment Investment and Management Company
10,ALCW,ASSISTED LIVING CONCEPTS INC NEV NEW W.I.,stocks,us,XNYS,CS,True,usd,0000929994,NaN,...,True,high,inactive,2006-11-09,http_404,D:\reference\overview\ticker=ALCW\overview_ALC...,ALC,True,overview_404,ASSISTED LIVING CONCEPTS INC NEV NEW W.I.
11,ALLEW,ALLEGION PUB LTD CO W.I. (IRL),stocks,us,XNYS,CS,True,usd,0001579241,NaN,...,True,high,inactive,2013-12-02,http_404,D:\reference\overview\ticker=ALLEW\overview_AL...,ALLE,True,overview_404,ALLEGION PUB LTD CO W.I. (IRL)
12,ALVW,"Autoliv, Inc.",stocks,us,XNYS,CS,True,usd,0001034670,NaN,...,True,high,inactive,2018-07-01,http_404,D:\reference\overview\ticker=ALVW\overview_ALV...,ALV,True,overview_404,"Autoliv, Inc."
13,AMFWW,AMEC FORSTER WHEELER PLC ADS,stocks,us,XNYS,CS,True,usd,NaN,NaN,...,True,high,inactive,2014-11-24,http_404,D:\reference\overview\ticker=AMFWW\overview_AM...,AMFW,True,overview_404,AMEC FORSTER WHEELER PLC ADS
14,AOLW,AOL INC COMMON STOCK WI,stocks,us,XNYS,CS,True,usd,0001468516,NaN,...,True,high,inactive,2009-12-09,http_404,D:\reference\overview\ticker=AOLW\overview_AOL...,AOL,True,overview_404,AOL INC COMMON STOCK WI
15,APTVW,Aptiv PLC,stocks,us,XNYS,CS,True,usd,0001521332,NaN,...,True,high,inactive,2017-12-04,http_404,D:\reference\overview\ticker=APTVW\overview_AP...,APTV,True,overview_404,Aptiv PLC
16,ARMKW,Aramark,stocks,us,XNYS,CS,True,usd,0001584509,BBG01JFXHPX8,...,True,high,inactive,2023-10-01,http_404,D:\reference\overview\ticker=ARMKW\overview_AR...,ARMK,True,overview_404,Aramark
17,ARPW,ATLAS RES PARTNERS L P COM UIT REPSTG LTD PTNR...,stocks,us,XNYS,CS,True,usd,0001532750,NaN,...,True,high,inactive,2012-03-13,http_404,D:\reference\overview\ticker=ARPW\overview_ARP...,ARP,True,overview_404,ATLAS RES PARTNERS L P COM UIT REPSTG LTD PTNR...
18,ASHW,Ashland Global Holdings Inc.,stocks,us,XNYS,CS,True,usd,0001674862,NaN,...,True,high,inactive,2017-05-14,http_404,D:\reference\overview\ticker=ASHW\overview_ASH...,ASH,True,overview_404,Ashland Global Holdings Inc.
19,ASXW,"ASE Industrial Holding Co., Ltd.",stocks,us,XNYS,CS,True,usd,NaN,BBG00KLHL9W6,...,True,high,inactive,2018-05-01,http_404,D:\reference\overview\ticker=ASXW\overview_ASX...,ASX,True,overview_404,"ASE Industrial Holding Co., Ltd."

,ticker,name,market,locale,primary_exchange,type,active,currency_name,cik,composite_figi,...,exchange_priority,has_composite_figi,has_share_class_figi,has_list_date,cut_frequency,first_seen_date,last_seen_date,latest_active,status_confidence,status
0,A,Agilent Technologies Inc.,stocks,us,XNYS,CS,True,usd,0001090872,BBG000BWQYZ5,...,1,1,1,0,daily,2022-02-08,2022-02-08,True,high,inactive
1,AA,"Alcoa, Inc.",stocks,us,XNYS,CS,True,usd,0000004281,NaN,...,1,0,0,0,daily,2005-01-01,2016-10-31,True,high,inactive
2,AAA,ALTANA AKTIENGESELLSCHAFT SPON ADR,stocks,us,XNYS,CS,True,usd,NaN,NaN,...,1,0,0,0,daily,2005-01-01,2007-05-21,True,high,inactive
3,AABA,Altaba Inc. Common Stock,stocks,us,XNAS,CS,True,usd,0001011006,BBG000KB2D74,...,0,1,1,0,daily,2017-06-19,2019-10-06,True,high,inactive
4,AAC,"ABLEAUCTIONS, COM, INC.",stocks,us,XASE,CS,True,usd,0001099290,NaN,...,2,0,0,0,daily,2008-10-03,2010-02-07,True,high,inactive

,ticker,name,market,locale,primary_exchange,type,active,currency_name,cik,composite_figi,...,exchange_priority,has_composite_figi,has_share_class_figi,has_list_date,cut_frequency,first_seen_date,last_seen_date,latest_active,status_confidence,status
12263,ZYBT,Zhengye Biotechnology Holding Limited Ordinary...,stocks,us,XNAS,CS,True,usd,0001975641,NaN,...,0,0,0,0,daily,2025-01-07,2026-03-09,True,high,active
12264,ZYME,Zymeworks Inc.,stocks,us,XNYS,CS,True,usd,0001403752,BBG00GD15LJ5,...,1,1,1,0,daily,2017-04-27,2022-10-12,True,high,inactive
12265,ZYNE,"Zynerba Pharmaceuticals, Inc",stocks,us,XNAS,CS,True,usd,0001621443,BBG007BBS8B7,...,0,1,1,0,daily,2016-10-25,2023-10-11,True,high,inactive
12266,ZYXI,ZYNEX INC,stocks,us,XNAS,CS,True,usd,0000846475,BBG000BJBXZ2,...,0,1,1,0,daily,2019-02-12,2025-12-23,True,high,inactive
12267,ZZ,SEALY CORPORATION COM,stocks,us,XNYS,CS,True,usd,0000748015,NaN,...,1,0,0,0,daily,2006-04-07,2013-03-18,True,high,inactive

Script:

build_tickers_2005_2026_upper_remapped_review.py

Artefactos creados:

- tickers_2005_2026_upper_remapped_review.parquet
- tickers_2005_2026_upper_remapped_review.csv
- tickers_2005_2026_upper_remapped_review.summary.json

Resultado real:

- rows_total: 200

Qué incluye:

- ticker_original
- ticker_suggested
- candidate_exists_in_upper
- full_name
- request_date
- msg
- datos del ticker sugerido en upper
- datos del ticker sugerido en full
- manual_review_status = pending
- review_note

---


Ahora mismo tienes 200 tickers que:

  - están en tu universo operativo
  - fallan en overview
  - muchos parecen W.I. o símbolos transitorios
  - pero tú sospechas que algunos deberían remapearse al ticker “base” sin sufijo

  Ese código sirve para esto:

  - separar los 200 problemáticos
  - proponer un ticker base candidato
  - dejar una tabla de revisión manual antes de tocar el universo real

  Lo que evita:

  - hacer remapeos automáticos peligrosos
  - por ejemplo convertir un preferente, when-issued o unidad en un common stock que no corresponde

  En corto:

  - upper_clean sirve para excluir lo que ahora rompe
  - remapped_review sirve para revisar, uno a uno, cuáles de esos excluidos sí quieres convertir a ticker
    base

  Si no quieres revisión manual y prefieres expulsarlos todos:

  - entonces este código no hace falta para la operativa inmediata
  - te basta con tickers_2005_2026_upper_clean.parquet

  Si quieres remapear parte de esos 200 con criterio:

  - entonces sí hace falta este artefacto de revisión

  Mi lectura práctica:

  - para seguir ya, usa upper_clean
  - el remapped_review solo sirve si quieres rescatar algunos tickers por validación manual contra
    TradeStation/u otra fuente

In [ ]:
from pathlib import Path
import json
import pandas as pd

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\build_tickers_2005_2026_upper_remapped_review.py")

exec(SCRIPT.read_text(encoding="utf-8"), globals(), globals())

summary = json.loads(Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\data\reference\universe_pti\tickers_2005_2026_upper_remapped_review.summary.json").read_text(encoding="utf-8"))
review = pd.read_parquet(r"C:\TSIS_Data\v1\backtest_SmallCaps\data\reference\universe_pti\tickers_2005_2026_upper_remapped_review.parquet")

print(json.dumps(summary, indent=2, ensure_ascii=False))
display(review.head(30))
display(review[review["candidate_exists_in_upper"] == True].head(30))

tickers_2005_2026_upper_remapped_review build completed
REVIEW_PARQUET: C:\TSIS_Data\v1\backtest_SmallCaps\data\reference\universe_pti\tickers_2005_2026_upper_remapped_review.parquet
REVIEW_CSV: C:\TSIS_Data\v1\backtest_SmallCaps\data\reference\universe_pti\tickers_2005_2026_upper_remapped_review.csv
SUMMARY_JSON: C:\TSIS_Data\v1\backtest_SmallCaps\data\reference\universe_pti\tickers_2005_2026_upper_remapped_review.summary.json
rows_total: 200
{
  "rows_total": 200,
  "candidate_exists_in_upper": 193,
  "paths": {
    "review_parquet": "C:\\TSIS_Data\\v1\\backtest_SmallCaps\\data\\reference\\universe_pti\\tickers_2005_2026_upper_remapped_review.parquet",
    "review_csv": "C:\\TSIS_Data\\v1\\backtest_SmallCaps\\data\\reference\\universe_pti\\tickers_2005_2026_upper_remapped_review.csv",
    "excluded_parquet": "C:\\TSIS_Data\\v1\\backtest_SmallCaps\\data\\reference\\universe_pti\\tickers_2005_2026_upper_excluded_overview404.parquet",
    "universe_upper": "C:\\TSIS_Data\\v1\\backtest_SmallCaps\\data\\reference\\universe_pti\\tickers_2005_2026_upper.parquet",
    "universe_full": "C:\\TSIS_Data\\v1\\backtest_SmallCaps\\data\\reference\\universe_pti\\tickers_2005_2026.parquet"
  }
}

,ticker_original,ticker_suggested,candidate_exists_in_upper,exclude_reason,full_name,request_date,msg,suggested_name_upper,suggested_status_upper,suggested_primary_exchange_upper,...,suggested_primary_exchange_full,suggested_entity_id_full,suggested_first_seen_date,suggested_last_seen_date,manual_review_status,review_note,out_file,suggested_base_exists_in_upper,ticker,suggested_base_ticker
0,ABHW,ABH,True,overview_404,ABITIBIBOWATER INC COM STK NEW (DE)W.I.,2010-12-19,http_404,ABITIBIBOWATER INC COM STK NEW (DE),inactive,XNYS,...,XNYS,ABH|XNYS,2007-10-29,2012-05-23,pending,None,D:\reference\overview\ticker=ABHW\overview_ABH...,True,ABHW,ABH
1,ABTW,ABT,True,overview_404,ABBOTT LABORATORIES COM STK (IL) EX-DIST W.I.,2013-01-01,http_404,Abbott Laboratories,active,XNYS,...,XNYS,BBG000B9ZXB4,2005-01-01,2026-03-09,pending,None,D:\reference\overview\ticker=ABTW\overview_ABT...,True,ABTW,ABT
2,ACTW,ACT,True,overview_404,ACTAVIS PLC COM SHS (IRL)W.I.,2014-07-01,http_404,ACTAVIS PLC COM SHS (IRL),inactive,XNYS,...,XNYS,ACT|XNYS,2013-01-25,2015-06-14,pending,None,D:\reference\overview\ticker=ACTW\overview_ACT...,True,ACTW,ACT
3,ACVW,ACV,True,overview_404,ALBERTO CULVER CO NEW W.I,2006-11-16,http_404,AllianzGI Diversified Income & Convertible Fun...,inactive,XNYS,...,XNYS,ACV|XNYS,2005-01-01,2019-09-05,pending,None,D:\reference\overview\ticker=ACVW\overview_ACV...,True,ACVW,ACV
4,ADNTW,ADNT,True,overview_404,Adient plc,2016-10-31,http_404,Adient plc Ordinary Shares,active,XNYS,...,XNYS,ADNT|XNYS,2016-10-31,2026-03-09,pending,None,D:\reference\overview\ticker=ADNTW\overview_AD...,True,ADNTW,ADNT
5,ADSW,ADS,False,overview_404,Alliance Data Systems Corporation,2021-11-07,http_404,NaN,NaN,NaN,...,NaN,NaN,None,None,pending,None,D:\reference\overview\ticker=ADSW\overview_ADS...,False,ADSW,ADS
6,ADTW,ADT,True,overview_404,ADT CORP W.I.,2012-09-30,http_404,ADT CORP,inactive,XNYS,...,XNYS,ADT|XNYS,2012-10-02,2016-05-02,pending,None,D:\reference\overview\ticker=ADTW\overview_ADT...,True,ADTW,ADT
7,AHLP,AHL,True,overview_404,ASPEN INS HLDGS LTD PERP PFD INCM EQTY REPL SE...,2005-12-14,http_404,Aspen Insurance Holdings Limited,inactive,XNYS,...,XNYS,AHL|XNYS,2005-01-01,2026-02-24,pending,None,D:\reference\overview\ticker=AHLP\overview_AHL...,True,AHLP,AHL
8,AHOW,AHO,True,overview_404,KONINKLIJKE AHOLD NV SPONSORED ADR 2007 W.I.,2007-08-28,http_404,KONINKLIJKE AHOLD NV SPONS ADR (EA RPSTG 1 ORD),inactive,XNYS,...,XNYS,AHO|XNYS,2005-01-01,2007-09-20,pending,None,D:\reference\overview\ticker=AHOW\overview_AHO...,True,AHOW,AHO
9,AHPW,AHP,True,overview_404,ASHFORD HOSPITALITY PRIME INC COM SK (MD) W.I.,2013-11-19,http_404,"Ashford Hospitality Prime, Inc.",inactive,XNYS,...,XNYS,AHP|XNYS,2013-11-21,2018-04-23,pending,None,D:\reference\overview\ticker=AHPW\overview_AHP...,True,AHPW,AHP
10,AIVW,AIV,True,overview_404,Apartment Investment and Management Company,2020-12-14,http_404,Apartment Investment & Mgmt,inactive,XNYS,...,XNYS,AIV|XNYS,2005-01-01,2019-02-20,pending,None,D:\reference\overview\ticker=AIVW\overview_AIV...,True,AIVW,AIV
11,ALCW,ALC,True,overview_404,ASSISTED LIVING CONCEPTS INC NEV NEW W.I.,2006-11-09,http_404,Alcon Inc. Ordinary Shares,active,XNYS,...,XNYS,ALC|XNYS,2006-11-10,2026-03-09,pending,None,D:\reference\overview\ticker=ALCW\overview_ALC...,True,ALCW,ALC
12,ALLEW,ALLE,True,overview_404,ALLEGION PUB LTD CO W.I. (IRL),2013-12-02,http_404,Allegion Public Limited Company,active,XNYS,...,XNYS,ALLE|XNYS,2013-12-03,2026-03-09,pending,None,D:\reference\overview\ticker=ALLEW\overview_AL...,True,ALLEW,ALLE
13,ALVW,ALV,True,overview_404,"Autoliv, Inc.",2018-07-01,http_404,"Autoliv, Inc.",active,XNYS,...,XNYS,BBG000BVLRY8,2005-01-01,2026-03-09,pending,None,D:\reference\overview\ticker=ALVW\overview_ALV...,True,ALVW,ALV
14,AMFWW,AMFW,True,overview_404,AMEC FORSTER WHEELER PLC ADS,2014-11-24,http_404,AMEC FOSTER WHEELER PLC,inactive,XNYS,...,XNYS,AMFW|XNYS,2014-11-26,2016-10-24,pending,None,D:\reference\overview\ticker=AMFWW\overview_AM...,True,AMFWW,AMFW
15,AOLW,AOL,True,overview_404,AOL INC COMMON STOCK WI,2009-12-09,http_404,AOL INC COMMON STOCK,inactive,XNYS,...,XNYS,AOL|XNYS,2010-01-20,2015-06-23,pending,None,D:\reference\overview\ticker=AOLW\overview_AOL...,True,AOLW,AOL
16,APTVW,APTV,True,overview_404,Aptiv PLC,2017-12-04,http_404,Aptiv PLC,active,XNYS,...,XNYS,APTV|XNYS,2017-12-05,2026-03-09,pending,None,D:\reference\overview\ticker=APTVW\overview_AP...,True,APTVW,APTV
17,ARMKW,ARMK,True,overview_404,Aramark,2023-10-01,http_404,ARAMARK,active,XNYS,...,XNYS,BBG001KY4N87,2013-12-16,2026-03-09,pending,None,D:\reference\overview\ticker=ARMKW\overview_AR...,True,ARMKW,ARMK
18,ARPW,ARP,True,overview_404,ATLAS RES PARTNERS L P COM UIT REPSTG LTD PTNR...,2012-03-13,http_404,ATLAS RESOURCE PARTNERS L P COM UIT REPSTG LTD...,inactive,XNYS,...,XNYS,ARP|XNYS,2005-02-04,2016-07-12,pending,None,D:\reference\overview\ticker=ARPW\overview_ARP...,True,ARPW,ARP
19,ASHW,ASH,True,overview_404,Ashland Global Holdings Inc.,2017-05-14,http_404,ASHLAND INC,inactive,XNYS,...,XNYS,ASH|XNYS,2005-01-01,2016-09-20,pending,None,D:\reference\overview\ticker=ASHW\overview_ASH...,True,ASHW,ASH
20,ASXW,ASX,True,overview_404,"ASE Industrial Holding Co., Ltd.",2018-05-01,http_404,AMER SEMI-COND ENG ADS (5CMSH),inactive,XNYS,...,XNYS,ASX|XNYS,2005-01-01,2016-10-24,pending,None,D:\reference\overview\ticker=ASXW\overview_ASX...,True,ASXW,ASX
21,AXLLW,AXLL,True,overview_404,AXIALL CORP COM STK (DE) W.I.,2013-02-04,http_404,AXIALL CORP COM STK (DE),inactive,XNYS,...,XNYS,AXLL|XNYS,2013-01-30,2016-08-31,pending,None,D:\reference\overview\ticker=AXLLW\overview_AX...,True,AXLLW,AXLL
22,BBUW,BBU,True,overview_404,Brookfield Business Partners L.P. Limited Part...,2022-03-14,http_404,Brookfield Business Partners L.P.Limited Partn...,active,XNYS,...,XNYS,BBU|XNYS,2016-06-21,2026-03-09,pending,None,D:\reference\overview\ticker=BBUW\overview_BBU...,True,BBUW,BBU
23,BDXW,BDX,True,overview_404,"Becton, Dickinson and Company",2022-03-31,http_404,"Becton, Dickinson and Co.",active,XNYS,...,XNYS,BBG000BCZYD3,2005-01-01,2026-03-09,pending,None,D:\reference\overview\ticker=BDXW\overview_BDX...,True,BDXW,BDX
24,BEPW,BEP,True,overview_404,Brookfield Renewable Partners L.P. Limited Par...,2020-07-29,http_404,Brookfield Renewable Partners L.P.,active,XNYS,...,XNYS,BEP|XNYS,2005-03-29,2026-03-09,pending,None,D:\reference\overview\ticker=BEPW\overview_BEP...,True,BEPW,BEP
25,BHVNW,BHVN,True,overview_404,Biohaven Ltd.,2022-10-04,http_404,Biohaven Ltd.,active,XNYS,...,XNYS,BHVN|XNYS,2017-05-03,2026-03-09,pending,None,D:\reference\overview\ticker=BHVNW\overview_BH...,True,BHVNW,BHVN
26,BIPW,BIP,True,overview_404,Brookfield Infrastructure Partners L.P. Limite...,2020-03-30,http_404,Brookfield Infrastructure Partners L.P. Limite...,active,XNYS,...,XNYS,BIP|XNYS,2008-02-04,2026-03-09,pending,None,D:\reference\overview\ticker=BIPW\overview_BIP...,True,BIPW,BIP
27,BNKW,BNK,True,overview_404,TD BANKNORTH INC. W.I.,2006-02-09,http_404,C1 FINL INC COM STK (FL),inactive,XNYS,...,XNYS,BNK|XNYS,2005-01-01,2016-07-21,pending,None,D:\reference\overview\ticker=BNKW\overview_BNK...,True,BNKW,BNK
28,BNW,BN,True,overview_404,Brookfield Corporation,2022-12-12,http_404,Brookfield Corporation,active,XNYS,...,XNYS,BBG000C9KL89,2005-11-15,2026-03-09,pending,None,D:\reference\overview\ticker=BNW\overview_BNW_...,True,BNW,BN
29,BPYW,BPY,True,overview_404,BROOKFIELD PPTY PARTNERS L P UIT LTD PARTNERSH...,2013-04-14,http_404,Brookfield Property Partners L.P. Limited Part...,inactive,XNAS,...,XNAS,BPY|XNAS,2017-11-16,2021-07-26,pending,None,D:\reference\overview\ticker=BPYW\overview_BPY...,True,BPYW,BPY

,ticker_original,ticker_suggested,candidate_exists_in_upper,exclude_reason,full_name,request_date,msg,suggested_name_upper,suggested_status_upper,suggested_primary_exchange_upper,...,suggested_primary_exchange_full,suggested_entity_id_full,suggested_first_seen_date,suggested_last_seen_date,manual_review_status,review_note,out_file,suggested_base_exists_in_upper,ticker,suggested_base_ticker
0,ABHW,ABH,True,overview_404,ABITIBIBOWATER INC COM STK NEW (DE)W.I.,2010-12-19,http_404,ABITIBIBOWATER INC COM STK NEW (DE),inactive,XNYS,...,XNYS,ABH|XNYS,2007-10-29,2012-05-23,pending,None,D:\reference\overview\ticker=ABHW\overview_ABH...,True,ABHW,ABH
1,ABTW,ABT,True,overview_404,ABBOTT LABORATORIES COM STK (IL) EX-DIST W.I.,2013-01-01,http_404,Abbott Laboratories,active,XNYS,...,XNYS,BBG000B9ZXB4,2005-01-01,2026-03-09,pending,None,D:\reference\overview\ticker=ABTW\overview_ABT...,True,ABTW,ABT
2,ACTW,ACT,True,overview_404,ACTAVIS PLC COM SHS (IRL)W.I.,2014-07-01,http_404,ACTAVIS PLC COM SHS (IRL),inactive,XNYS,...,XNYS,ACT|XNYS,2013-01-25,2015-06-14,pending,None,D:\reference\overview\ticker=ACTW\overview_ACT...,True,ACTW,ACT
3,ACVW,ACV,True,overview_404,ALBERTO CULVER CO NEW W.I,2006-11-16,http_404,AllianzGI Diversified Income & Convertible Fun...,inactive,XNYS,...,XNYS,ACV|XNYS,2005-01-01,2019-09-05,pending,None,D:\reference\overview\ticker=ACVW\overview_ACV...,True,ACVW,ACV
4,ADNTW,ADNT,True,overview_404,Adient plc,2016-10-31,http_404,Adient plc Ordinary Shares,active,XNYS,...,XNYS,ADNT|XNYS,2016-10-31,2026-03-09,pending,None,D:\reference\overview\ticker=ADNTW\overview_AD...,True,ADNTW,ADNT
6,ADTW,ADT,True,overview_404,ADT CORP W.I.,2012-09-30,http_404,ADT CORP,inactive,XNYS,...,XNYS,ADT|XNYS,2012-10-02,2016-05-02,pending,None,D:\reference\overview\ticker=ADTW\overview_ADT...,True,ADTW,ADT
7,AHLP,AHL,True,overview_404,ASPEN INS HLDGS LTD PERP PFD INCM EQTY REPL SE...,2005-12-14,http_404,Aspen Insurance Holdings Limited,inactive,XNYS,...,XNYS,AHL|XNYS,2005-01-01,2026-02-24,pending,None,D:\reference\overview\ticker=AHLP\overview_AHL...,True,AHLP,AHL
8,AHOW,AHO,True,overview_404,KONINKLIJKE AHOLD NV SPONSORED ADR 2007 W.I.,2007-08-28,http_404,KONINKLIJKE AHOLD NV SPONS ADR (EA RPSTG 1 ORD),inactive,XNYS,...,XNYS,AHO|XNYS,2005-01-01,2007-09-20,pending,None,D:\reference\overview\ticker=AHOW\overview_AHO...,True,AHOW,AHO
9,AHPW,AHP,True,overview_404,ASHFORD HOSPITALITY PRIME INC COM SK (MD) W.I.,2013-11-19,http_404,"Ashford Hospitality Prime, Inc.",inactive,XNYS,...,XNYS,AHP|XNYS,2013-11-21,2018-04-23,pending,None,D:\reference\overview\ticker=AHPW\overview_AHP...,True,AHPW,AHP
10,AIVW,AIV,True,overview_404,Apartment Investment and Management Company,2020-12-14,http_404,Apartment Investment & Mgmt,inactive,XNYS,...,XNYS,AIV|XNYS,2005-01-01,2019-02-20,pending,None,D:\reference\overview\ticker=AIVW\overview_AIV...,True,AIVW,AIV
11,ALCW,ALC,True,overview_404,ASSISTED LIVING CONCEPTS INC NEV NEW W.I.,2006-11-09,http_404,Alcon Inc. Ordinary Shares,active,XNYS,...,XNYS,ALC|XNYS,2006-11-10,2026-03-09,pending,None,D:\reference\overview\ticker=ALCW\overview_ALC...,True,ALCW,ALC
12,ALLEW,ALLE,True,overview_404,ALLEGION PUB LTD CO W.I. (IRL),2013-12-02,http_404,Allegion Public Limited Company,active,XNYS,...,XNYS,ALLE|XNYS,2013-12-03,2026-03-09,pending,None,D:\reference\overview\ticker=ALLEW\overview_AL...,True,ALLEW,ALLE
13,ALVW,ALV,True,overview_404,"Autoliv, Inc.",2018-07-01,http_404,"Autoliv, Inc.",active,XNYS,...,XNYS,BBG000BVLRY8,2005-01-01,2026-03-09,pending,None,D:\reference\overview\ticker=ALVW\overview_ALV...,True,ALVW,ALV
14,AMFWW,AMFW,True,overview_404,AMEC FORSTER WHEELER PLC ADS,2014-11-24,http_404,AMEC FOSTER WHEELER PLC,inactive,XNYS,...,XNYS,AMFW|XNYS,2014-11-26,2016-10-24,pending,None,D:\reference\overview\ticker=AMFWW\overview_AM...,True,AMFWW,AMFW
15,AOLW,AOL,True,overview_404,AOL INC COMMON STOCK WI,2009-12-09,http_404,AOL INC COMMON STOCK,inactive,XNYS,...,XNYS,AOL|XNYS,2010-01-20,2015-06-23,pending,None,D:\reference\overview\ticker=AOLW\overview_AOL...,True,AOLW,AOL
16,APTVW,APTV,True,overview_404,Aptiv PLC,2017-12-04,http_404,Aptiv PLC,active,XNYS,...,XNYS,APTV|XNYS,2017-12-05,2026-03-09,pending,None,D:\reference\overview\ticker=APTVW\overview_AP...,True,APTVW,APTV
17,ARMKW,ARMK,True,overview_404,Aramark,2023-10-01,http_404,ARAMARK,active,XNYS,...,XNYS,BBG001KY4N87,2013-12-16,2026-03-09,pending,None,D:\reference\overview\ticker=ARMKW\overview_AR...,True,ARMKW,ARMK
18,ARPW,ARP,True,overview_404,ATLAS RES PARTNERS L P COM UIT REPSTG LTD PTNR...,2012-03-13,http_404,ATLAS RESOURCE PARTNERS L P COM UIT REPSTG LTD...,inactive,XNYS,...,XNYS,ARP|XNYS,2005-02-04,2016-07-12,pending,None,D:\reference\overview\ticker=ARPW\overview_ARP...,True,ARPW,ARP
19,ASHW,ASH,True,overview_404,Ashland Global Holdings Inc.,2017-05-14,http_404,ASHLAND INC,inactive,XNYS,...,XNYS,ASH|XNYS,2005-01-01,2016-09-20,pending,None,D:\reference\overview\ticker=ASHW\overview_ASH...,True,ASHW,ASH
20,ASXW,ASX,True,overview_404,"ASE Industrial Holding Co., Ltd.",2018-05-01,http_404,AMER SEMI-COND ENG ADS (5CMSH),inactive,XNYS,...,XNYS,ASX|XNYS,2005-01-01,2016-10-24,pending,None,D:\reference\overview\ticker=ASXW\overview_ASX...,True,ASXW,ASX
21,AXLLW,AXLL,True,overview_404,AXIALL CORP COM STK (DE) W.I.,2013-02-04,http_404,AXIALL CORP COM STK (DE),inactive,XNYS,...,XNYS,AXLL|XNYS,2013-01-30,2016-08-31,pending,None,D:\reference\overview\ticker=AXLLW\overview_AX...,True,AXLLW,AXLL
22,BBUW,BBU,True,overview_404,Brookfield Business Partners L.P. Limited Part...,2022-03-14,http_404,Brookfield Business Partners L.P.Limited Partn...,active,XNYS,...,XNYS,BBU|XNYS,2016-06-21,2026-03-09,pending,None,D:\reference\overview\ticker=BBUW\overview_BBU...,True,BBUW,BBU
23,BDXW,BDX,True,overview_404,"Becton, Dickinson and Company",2022-03-31,http_404,"Becton, Dickinson and Co.",active,XNYS,...,XNYS,BBG000BCZYD3,2005-01-01,2026-03-09,pending,None,D:\reference\overview\ticker=BDXW\overview_BDX...,True,BDXW,BDX
24,BEPW,BEP,True,overview_404,Brookfield Renewable Partners L.P. Limited Par...,2020-07-29,http_404,Brookfield Renewable Partners L.P.,active,XNYS,...,XNYS,BEP|XNYS,2005-03-29,2026-03-09,pending,None,D:\reference\overview\ticker=BEPW\overview_BEP...,True,BEPW,BEP
25,BHVNW,BHVN,True,overview_404,Biohaven Ltd.,2022-10-04,http_404,Biohaven Ltd.,active,XNYS,...,XNYS,BHVN|XNYS,2017-05-03,2026-03-09,pending,None,D:\reference\overview\ticker=BHVNW\overview_BH...,True,BHVNW,BHVN
26,BIPW,BIP,True,overview_404,Brookfield Infrastructure Partners L.P. Limite...,2020-03-30,http_404,Brookfield Infrastructure Partners L.P. Limite...,active,XNYS,...,XNYS,BIP|XNYS,2008-02-04,2026-03-09,pending,None,D:\reference\overview\ticker=BIPW\overview_BIP...,True,BIPW,BIP
27,BNKW,BNK,True,overview_404,TD BANKNORTH INC. W.I.,2006-02-09,http_404,C1 FINL INC COM STK (FL),inactive,XNYS,...,XNYS,BNK|XNYS,2005-01-01,2016-07-21,pending,None,D:\reference\overview\ticker=BNKW\overview_BNK...,True,BNKW,BNK
28,BNW,BN,True,overview_404,Brookfield Corporation,2022-12-12,http_404,Brookfield Corporation,active,XNYS,...,XNYS,BBG000C9KL89,2005-11-15,2026-03-09,pending,None,D:\reference\overview\ticker=BNW\overview_BNW_...,True,BNW,BN
29,BPYW,BPY,True,overview_404,BROOKFIELD PPTY PARTNERS L P UIT LTD PARTNERSH...,2013-04-14,http_404,Brookfield Property Partners L.P. Limited Part...,inactive,XNAS,...,XNAS,BPY|XNAS,2017-11-16,2021-07-26,pending,None,D:\reference\overview\ticker=BPYW\overview_BPY...,True,BPYW,BPY
30,BTXW,BTX,True,overview_404,BIOTIME INC EX-DISTRIBUTION WI,2016-01-03,http_404,"Biotime, Inc.",inactive,XASE,...,XASE,BBG00JQ541N6,2009-11-02,2019-08-11,pending,None,D:\reference\overview\ticker=BTXW\overview_BTX...,True,BTXW,BTX