
## Ejemplo visual de los datos en files parker

**Day Aggregates** : FALTA
- S3: `us_stocks_sip/day_aggs_v1`
- OHLCV diario por equity US.
- local : 

**Minute Aggregates**
- S3: `us_stocks_sip/minute_aggs_v1`
- OHLCV por minuto.
- local : `C:\TSIS_Data\data\ohlcv_intraday_1m\2004_2018\{ticker}\year=YYYY\month=MM\minute.parquet`

In [74]:
from pathlib import Path

# --- Controles de vista ---
HEAD_N = 5
TRANSPOSE = False                 # script 004 (foto parquet)

# --- 1) Foto del parquet minute ---
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\004_minute_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

# --- 2) Tabla de atributos + diccionario técnico ---
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\104_minute_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\ohlcv_intraday_1m\2004_2018\AACB\year=2004\month=01\minute.parquet
rows: 312
row_groups: 1
columns: 12

Schema literal:
volume: int64
vwap: double
open: double
close: double
high: double
low: double
t: int64
transactions: int64
timestamp: timestamp[ms]
ticker: large_string
date: date32[day]
minute: large_string
year: dictionary<values=int32, indices=int32, ordered=0>
month: dictionary<values=int32, indices=int32, ordered=0>

Primeras 5 filas literales:

,volume,vwap,open,close,high,low,t,transactions,timestamp,ticker,date,minute,year,month
0,400,15.2395,15.239,15.24,15.24,15.239,1073065980000,4,2004-01-02 17:53:00,AACB,2004-01-02,2004-01-02 17:53,2004,1
1,100,15.2100,15.210,15.21,15.21,15.210,1073066580000,1,2004-01-02 18:03:00,AACB,2004-01-02,2004-01-02 18:03,2004,1
2,100,15.1800,15.180,15.18,15.18,15.180,1073066640000,1,2004-01-02 18:04:00,AACB,2004-01-02,2004-01-02 18:04,2004,1
3,500,15.2420,15.190,15.32,15.32,15.190,1073066880000,3,2004-01-02 18:08:00,AACB,2004-01-02,2004-01-02 18:08,2004,1
4,300,15.2900,15.290,15.29,15.29,15.290,1073067180000,2,2004-01-02 18:13:00,AACB,2004-01-02,2004-01-02 18:13,2004,1

Rango timestamp: 2004-01-02 17:53:00 -> 2004-01-30 20:54:00
Rango date: 2004-01-02 00:00:00 -> 2004-01-30 00:00:00
FILE: C:\TSIS_Data\data\ohlcv_intraday_1m\2004_2018\AACB\year=2004\month=01\minute.parquet
rows: 312
row_groups: 1
columns: 12
minute.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "ticker": {
    "definicion": "Simbolo del activo (equity) al que pertenece la barra.",
    "tipo_esperado": "string",
    "origen_oficial": "Flat Files minute aggs sample / REST aggregates",
    "mapeo_api": "ticker / sym",
    "nota_local": "Identificador del ticker en el parquet local.",
    "source_url": "https://massive.com/docs/flat-files/stocks/minute-aggregates",
    "certeza": "oficial"
  },
  "open": {
    "definicion": "Precio de apertura de la ventana de agregacion (1 minuto).",
    "tipo_esperado": "number",
    "origen_oficial": "REST aggregates custom bars",
    "mapeo_api": "o",
    "nota_local": "Corresponde al open de la vela por minuto.",
    "source_url": "https://polygon.io/docs/rest/stocks/aggregates/custom-bars",
    "certeza": "oficial"
  },
  "high": {
    "definicion": "Precio maximo dentro de la ventana de agregacion.",
    "tipo_esperado": "number",
    "origen_oficial": "REST aggregates custom bars",
    "mapeo_api": "h",
    "nota_local": "Maximo de la vela por minuto.",
    "source_url": "https://polygon.io/docs/rest/stocks/aggregates/custom-bars",
    "certeza": "oficial"
  },
  "low": {
    "definicion": "Precio minimo dentro de la ventana de agregacion.",
    "tipo_esperado": "number",
    "origen_oficial": "REST aggregates custom bars",
    "mapeo_api": "l",
    "nota_local": "Minimo de la vela por minuto.",
    "source_url": "https://polygon.io/docs/rest/stocks/aggregates/custom-bars",
    "certeza": "oficial"
  },
  "close": {
    "definicion": "Precio de cierre de la ventana de agregacion.",
    "tipo_esperado": "number",
    "origen_oficial": "REST aggregates custom bars",
    "mapeo_api": "c",
    "nota_local": "Close de la vela por minuto.",
    "source_url": "https://polygon.io/docs/rest/stocks/aggregates/custom-bars",
    "certeza": "oficial"
  },
  "volume": {
    "definicion": "Volumen negociado en la ventana (suma de size de trades elegibles).",
    "tipo_esperado": "number",
    "origen_oficial": "REST aggregates custom bars / Flat Files minute aggs",
    "mapeo_api": "v",
    "nota_local": "Volumen por minuto en el parquet local.",
    "source_url": "https://polygon.io/docs/rest/stocks/aggregates/custom-bars",
    "certeza": "oficial"
  },
  "vwap": {
    "definicion": "Volume Weighted Average Price de la ventana.",
    "tipo_esperado": "number",
    "origen_oficial": "REST aggregates custom bars",
    "mapeo_api": "vw",
    "nota_local": "VWAP por minuto.",
    "source_url": "https://polygon.io/docs/rest/stocks/aggregates/custom-bars",
    "certeza": "oficial"
  },
  "transactions": {
    "definicion": "Numero de transacciones que componen la agregacion.",
    "tipo_esperado": "integer",
    "origen_oficial": "REST aggregates custom bars / Flat Files sample",
    "mapeo_api": "n / transactions",
    "nota_local": "Conteo de trades en el minuto.",
    "source_url": "https://polygon.io/docs/rest/stocks/aggregates/custom-bars",
    "certeza": "oficial"
  },
  "t": {
    "definicion": "Timestamp de inicio de la ventana de agregacion.",
    "tipo_esperado": "integer (epoch)",
    "origen_oficial": "REST aggregates custom bars",
    "mapeo_api": "t",
    "nota_local": "En este dataset local se observa en milisegundos Unix. Inferido por valores y schema timestamp[ms].",
    "source_url": "https://polygon.io/docs/rest/stocks/aggregates/custom-bars",
    "certeza": "oficial+inferencia_local"
  },
  "timestamp": {
    "definicion": "Marca temporal de la barra en formato datetime del parquet local.",
    "tipo_esperado": "timestamp",
    "origen_oficial": "Derivado local de window_start/t",
    "mapeo_api": "window_start / t (normalizado)",
    "nota_local": "Representacion legible del inicio de ventana por minuto.",
    "source_url": "https://massive.com/docs/flat-files/stocks/minute-aggregates",
    "certeza": "inferido_local"
  },
  "date": {
    "definicion": "Fecha de mercado (dia) asociada a la barra.",
    "tipo_esperado": "date",
    "origen_oficial": "Derivado local",
    "mapeo_api": "derivado de timestamp",
    "nota_local": "Campo auxiliar para particion/analitica diaria.",
    "source_url": "N/A",
    "certeza": "inferido_local"
  },
  "minute": {
    "definicion": "Etiqueta textual del minuto (YYYY-MM-DD HH:MM).",
    "tipo_esperado": "string",
    "origen_oficial": "Derivado local",
    "mapeo_api": "derivado de timestamp",
    "nota_local": "Campo auxiliar de presentacion.",
    "source_url": "N/A",
    "certeza": "inferido_local"
  },
  "year": {
    "definicion": "Ano de particion del almacenamiento local.",
    "tipo_esperado": "integer/category",
    "origen_oficial": "Particion local",
    "mapeo_api": "N/A",
    "nota_local": "No es variable de mercado; es organizacion de carpetas.",
    "source_url": "N/A",
    "certeza": "particion_local"
  },
  "month": {
    "definicion": "Mes de particion del almacenamiento local.",
    "tipo_esperado": "integer/category",
    "origen_oficial": "Particion local",
    "mapeo_api": "N/A",
    "nota_local": "No es variable de mercado; es organizacion de carpetas.",
    "source_url": "N/A",
    "certeza": "particion_local"
  }
}

**Trades (tick-level)**
- S3: `us_stocks_sip/trades_v1`
- Trades con timestamp ns.
- local : `C:\TSIS_Data\data\trades_ticks_2004_2018\{ticker}\year=YYYY\month=MM\day=YYYY-MM-DD\market.parquet`

In [75]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\005_market_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\105_market_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\trades_ticks_2004_2018\AACB\year=2004\month=01\day=2004-01-02\market.parquet
rows: 19
row_groups: 1
columns: 5

Schema literal:
timestamp: int64
price: double
size: int64
exchange: int64
conditions: large_string
year: dictionary<values=int32, indices=int32, ordered=0>
month: dictionary<values=int32, indices=int32, ordered=0>
day: dictionary<values=string, indices=int32, ordered=0>

Primeras 5 filas literales:

,timestamp,price,size,exchange,conditions,year,month,day
0,1073076695000000000,15.35,100,2,,2004,1,2004-01-02
1,1073076167000000000,15.35,100,2,,2004,1,2004-01-02
2,1073075838000000000,15.32,100,11,,2004,1,2004-01-02
3,1073074573000000000,15.30,100,11,,2004,1,2004-01-02
4,1073073790000000000,15.30,100,11,,2004,1,2004-01-02

Rango timestamp: 2004-01-02 17:53:13 -> 2004-01-02 20:51:35
FILE: C:\TSIS_Data\data\trades_ticks_2004_2018\AACB\year=2004\month=01\day=2004-01-02\market.parquet
rows: 19
row_groups: 1
columns: 5
market.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "timestamp": {
    "definicion": "Timestamp SIP del trade.",
    "tipo_esperado": "integer (epoch ns)",
    "origen_oficial": "Stocks Trades endpoint / trades_v1",
    "mapeo_api": "sip_timestamp / t",
    "nota_local": "En market.parquet suele venir como int64 en nanosegundos.",
    "source_url": "https://polygon.io/docs/rest/stocks/trades-quotes/trades",
    "certeza": "oficial+inferencia_local"
  },
  "price": {
    "definicion": "Precio ejecutado del trade.",
    "tipo_esperado": "number",
    "origen_oficial": "Stocks Trades endpoint / trades_v1",
    "mapeo_api": "price / p",
    "nota_local": "Precio por tick de transaccion.",
    "source_url": "https://polygon.io/docs/rest/stocks/trades-quotes/trades",
    "certeza": "oficial"
  },
  "size": {
    "definicion": "Cantidad de acciones negociadas en el trade.",
    "tipo_esperado": "integer",
    "origen_oficial": "Stocks Trades endpoint / trades_v1",
    "mapeo_api": "size / s",
    "nota_local": "Volumen unitario del trade.",
    "source_url": "https://polygon.io/docs/rest/stocks/trades-quotes/trades",
    "certeza": "oficial"
  },
  "exchange": {
    "definicion": "Identificador de exchange donde se reporta la ejecucion.",
    "tipo_esperado": "integer",
    "origen_oficial": "Stocks Trades endpoint / reference exchanges",
    "mapeo_api": "exchange / x",
    "nota_local": "Se puede mapear con tablas de exchanges de referencia.",
    "source_url": "https://polygon.io/docs/rest/stocks/trades-quotes/trades",
    "certeza": "oficial"
  },
  "conditions": {
    "definicion": "Condiciones de ejecucion del trade (trade conditions).",
    "tipo_esperado": "string/list",
    "origen_oficial": "Stocks Trades endpoint",
    "mapeo_api": "conditions / c",
    "nota_local": "En este parquet aparece como texto; puede variar por pipeline.",
    "source_url": "https://polygon.io/docs/rest/stocks/trades-quotes/trades",
    "certeza": "oficial+inferencia_local"
  },
  "year": {
    "definicion": "Ano de particion del almacenamiento local.",
    "tipo_esperado": "integer/category",
    "origen_oficial": "Particion local",
    "mapeo_api": "N/A",
    "nota_local": "No es variable de mercado; organiza carpetas.",
    "source_url": "N/A",
    "certeza": "particion_local"
  },
  "month": {
    "definicion": "Mes de particion del almacenamiento local.",
    "tipo_esperado": "integer/category",
    "origen_oficial": "Particion local",
    "mapeo_api": "N/A",
    "nota_local": "No es variable de mercado; organiza carpetas.",
    "source_url": "N/A",
    "certeza": "particion_local"
  },
  "day": {
    "definicion": "Dia de particion del almacenamiento local.",
    "tipo_esperado": "string/date/category",
    "origen_oficial": "Particion local",
    "mapeo_api": "N/A",
    "nota_local": "No es variable de mercado; organiza carpetas.",
    "source_url": "N/A",
    "certeza": "particion_local"
  }
}

**Quotes (NBBO tick-level)**
- S3: `us_stocks_sip/quotes_v1`
- Top-of-book con timestamp ns.
- local : `C:\TSIS_Data\data\quotes_p95\{ticker}\year=YYYY\month=MM\day=DD\quotes.parquet`

In [76]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\006_quotes_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\106_quotes_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\quotes_p95\AABA\year=2019\month=01\day=02\quotes.parquet
rows: 159598
row_groups: 1
columns: 12

Schema literal:
ask_exchange: int64
ask_price: double
ask_size: int64
bid_exchange: int64
bid_price: double
bid_size: int64
conditions: large_list<element: int64>
  child 0, element: int64
participant_timestamp: int64
sequence_number: int64
timestamp: int64
tape: int64
indicators: large_list<element: int64>
  child 0, element: int64
year: dictionary<values=int32, indices=int32, ordered=0>
month: dictionary<values=int32, indices=int32, ordered=0>
day: dictionary<values=int32, indices=int32, ordered=0>

Primeras 5 filas literales:

,ask_exchange,ask_price,ask_size,bid_exchange,bid_price,bid_size,conditions,participant_timestamp,sequence_number,timestamp,tape,indicators,year,month,day
0,18,57.17,200,15,56.33,700,[1],1546439400000189852,303792,1546439400060097104,3,None,2019,1,2
1,12,57.17,1000,15,56.33,700,[1],1546439400297882330,305701,1546439400297899484,3,None,2019,1,2
2,12,57.17,1000,2,56.38,300,[1],1546439400319048147,306018,1546439400319064390,3,None,2019,1,2
3,12,57.17,2000,2,56.38,300,[1],1546439400463833200,307975,1546439400463852123,3,None,2019,1,2
4,7,57.17,5200,2,56.38,300,[1],1546439400685353000,310328,1546439400685553615,3,None,2019,1,2

Rango timestamp: 2019-01-02 14:30:00.060097104 -> 2019-01-02 20:59:58.096767649
FILE: C:\TSIS_Data\data\quotes_p95\AABA\year=2019\month=01\day=02\quotes.parquet
rows: 159598
row_groups: 1
columns: 12
quotes.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "ask_exchange": {
    "definicion": "Exchange del mejor ask (oferta) en NBBO.",
    "tipo_esperado": "integer",
    "origen_oficial": "Stocks Quotes endpoint / quotes_v1",
    "mapeo_api": "ask_exchange / ax",
    "nota_local": "Codigo de venue para la punta ask.",
    "source_url": "https://polygon.io/docs/rest/stocks/trades-quotes/quotes",
    "certeza": "oficial"
  },
  "ask_price": {
    "definicion": "Precio del mejor ask en ese instante.",
    "tipo_esperado": "number",
    "origen_oficial": "Stocks Quotes endpoint / quotes_v1",
    "mapeo_api": "ask_price / ap",
    "nota_local": "Top-of-book lado vendedor.",
    "source_url": "https://polygon.io/docs/rest/stocks/trades-quotes/quotes",
    "certeza": "oficial"
  },
  "ask_size": {
    "definicion": "Tamano del mejor ask.",
    "tipo_esperado": "integer",
    "origen_oficial": "Stocks Quotes endpoint / quotes_v1",
    "mapeo_api": "ask_size / as",
    "nota_local": "Cantidad de acciones disponibles al ask.",
    "source_url": "https://polygon.io/docs/rest/stocks/trades-quotes/quotes",
    "certeza": "oficial"
  },
  "bid_exchange": {
    "definicion": "Exchange del mejor bid (demanda) en NBBO.",
    "tipo_esperado": "integer",
    "origen_oficial": "Stocks Quotes endpoint / quotes_v1",
    "mapeo_api": "bid_exchange / bx",
    "nota_local": "Codigo de venue para la punta bid.",
    "source_url": "https://polygon.io/docs/rest/stocks/trades-quotes/quotes",
    "certeza": "oficial"
  },
  "bid_price": {
    "definicion": "Precio del mejor bid en ese instante.",
    "tipo_esperado": "number",
    "origen_oficial": "Stocks Quotes endpoint / quotes_v1",
    "mapeo_api": "bid_price / bp",
    "nota_local": "Top-of-book lado comprador.",
    "source_url": "https://polygon.io/docs/rest/stocks/trades-quotes/quotes",
    "certeza": "oficial"
  },
  "bid_size": {
    "definicion": "Tamano del mejor bid.",
    "tipo_esperado": "integer",
    "origen_oficial": "Stocks Quotes endpoint / quotes_v1",
    "mapeo_api": "bid_size / bs",
    "nota_local": "Cantidad de acciones disponibles al bid.",
    "source_url": "https://polygon.io/docs/rest/stocks/trades-quotes/quotes",
    "certeza": "oficial"
  },
  "conditions": {
    "definicion": "Lista de condiciones de quote publicadas por SIP.",
    "tipo_esperado": "list[integer]",
    "origen_oficial": "Stocks Quotes endpoint",
    "mapeo_api": "conditions / c",
    "nota_local": "Codigos de condicion para filtrar/interpretar quote.",
    "source_url": "https://polygon.io/docs/rest/stocks/trades-quotes/quotes",
    "certeza": "oficial"
  },
  "participant_timestamp": {
    "definicion": "Timestamp del participante/venue que origina el quote.",
    "tipo_esperado": "integer (epoch ns)",
    "origen_oficial": "Stocks Quotes endpoint",
    "mapeo_api": "participant_timestamp / y",
    "nota_local": "Puede diferir del timestamp SIP.",
    "source_url": "https://polygon.io/docs/rest/stocks/trades-quotes/quotes",
    "certeza": "oficial"
  },
  "sequence_number": {
    "definicion": "Secuencia monotona del mensaje dentro del feed.",
    "tipo_esperado": "integer",
    "origen_oficial": "Stocks Quotes endpoint",
    "mapeo_api": "sequence_number / q",
    "nota_local": "Ayuda a ordenar eventos con mismo timestamp.",
    "source_url": "https://polygon.io/docs/rest/stocks/trades-quotes/quotes",
    "certeza": "oficial"
  },
  "timestamp": {
    "definicion": "Timestamp SIP del quote.",
    "tipo_esperado": "integer (epoch ns)",
    "origen_oficial": "Stocks Quotes endpoint / quotes_v1",
    "mapeo_api": "sip_timestamp / t",
    "nota_local": "Marca temporal principal del evento NBBO.",
    "source_url": "https://polygon.io/docs/rest/stocks/trades-quotes/quotes",
    "certeza": "oficial+inferencia_local"
  },
  "tape": {
    "definicion": "Tape SIP (A/B/C) codificado numericamente.",
    "tipo_esperado": "integer",
    "origen_oficial": "Stocks Quotes endpoint",
    "mapeo_api": "tape / z",
    "nota_local": "Clasifica la consolidacion SIP del quote.",
    "source_url": "https://polygon.io/docs/rest/stocks/trades-quotes/quotes",
    "certeza": "oficial"
  },
  "indicators": {
    "definicion": "Indicadores adicionales del quote.",
    "tipo_esperado": "list[integer]",
    "origen_oficial": "Stocks Quotes endpoint",
    "mapeo_api": "indicators / i",
    "nota_local": "Banderas de calidad/estado del quote segun feed.",
    "source_url": "https://polygon.io/docs/rest/stocks/trades-quotes/quotes",
    "certeza": "oficial"
  },
  "year": {
    "definicion": "Ano de particion del almacenamiento local.",
    "tipo_esperado": "integer/category",
    "origen_oficial": "Particion local",
    "mapeo_api": "N/A",
    "nota_local": "No es variable de mercado; organiza carpetas.",
    "source_url": "N/A",
    "certeza": "particion_local"
  },
  "month": {
    "definicion": "Mes de particion del almacenamiento local.",
    "tipo_esperado": "integer/category",
    "origen_oficial": "Particion local",
    "mapeo_api": "N/A",
    "nota_local": "No es variable de mercado; organiza carpetas.",
    "source_url": "N/A",
    "certeza": "particion_local"
  },
  "day": {
    "definicion": "Dia de particion del almacenamiento local.",
    "tipo_esperado": "integer/string/category",
    "origen_oficial": "Particion local",
    "mapeo_api": "N/A",
    "nota_local": "No es variable de mercado; organiza carpetas.",
    "source_url": "N/A",
    "certeza": "particion_local"
  }
}

**Ticker Events**
- REST: `reference/tickers/{id}/events`
- Eventos de ticker (ticker_change, etc.).
- local : `C:\TSIS_Data\data\additional\corporate_actions\ticker_events.parquet`

In [122]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\009_ticker_events_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

from pathlib import Path
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\109_ticker_events_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\additional\corporate_actions\ticker_events.parquet
rows: 3766
row_groups: 1
columns: 4

Schema literal:
ticker: large_string
ticker_change: struct<ticker: large_string>
  child 0, ticker: large_string
type: large_string
date: large_string

Primeras 5 filas literales:

  ticker       ticker_change           type        date
0   AACB  {'ticker': 'AACB'}  ticker_change  2025-04-07
1   AAGR  {'ticker': 'AAGR'}  ticker_change  1969-12-31
2    AAM   {'ticker': 'AAM'}  ticker_change  2024-09-16
3   AAME  {'ticker': 'AAME'}  ticker_change  2003-09-10
4   AAMI  {'ticker': 'AAMI'}  ticker_change  2025-01-02

Rango date: 1969-12-31 00:00:00 -> 2025-11-21 00:00:00
FILE: C:\TSIS_Data\data\additional\corporate_actions\ticker_events.parquet
rows: 3766
row_groups: 1
columns: 4
ticker_events.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "ticker": {
    "definicion": "Simbolo del activo.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Ticker Events",
    "mapeo_api": "ticker/sym",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_vx_reference_tickers__ticker__events",
    "certeza": "oficial+inferencia_local"
  },
  "ticker_change": {
    "definicion": "Campo 'ticker_change' presente en este parquet.",
    "tipo_esperado": "struct<ticker: large_string>",
    "origen_oficial": "Reference - Ticker Events",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_vx_reference_tickers__ticker__events",
    "certeza": "oficial+inferencia_local"
  },
  "type": {
    "definicion": "Campo 'type' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Ticker Events",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_vx_reference_tickers__ticker__events",
    "certeza": "oficial+inferencia_local"
  },
  "date": {
    "definicion": "Fecha asociada al registro.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Ticker Events",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_vx_reference_tickers__ticker__events",
    "certeza": "oficial+inferencia_local"
  }
}

**Splits**
- REST: `reference/splits`
- Corporate action (splits).
- local : `C:\TSIS_Data\data\additional\corporate_actions\splits.parquet`

In [167]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\007_splits_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\107_splits_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\additional\corporate_actions\splits.parquet
rows: 26812
row_groups: 1
columns: 5

Schema literal:
execution_date: large_string
id: large_string
split_from: double
split_to: double
ticker: large_string

Primeras 5 filas literales:

,execution_date,id,split_from,split_to,ticker
0,2026-03-30,E0f5653c619604b99f1cb07e7a995b73f6ea613135f69c...,1.0,5.00,SGBKF
1,2026-01-06,E48e44b1448b773e7c07ddc880f3ff8323f5caf787d3d7...,1.0,10.00,ITOCY
2,2025-12-29,E557f0be1e36cd18048fb174008b033d565ec995d28f90...,1.0,2.00,MBUMF
3,2025-12-19,Efe0ea5c3ab2c315ffce9c42178fe887bd452f34588918...,1.0,1.05,MLGF
4,2025-12-15,E6b5ce554540f3a217a0a7fcff9a62c1538c73a0e3f941...,1.0,100.00,INVMF

Rango execution_date: 1978-10-25 00:00:00 -> 2026-03-30 00:00:00
FILE: C:\TSIS_Data\data\additional\corporate_actions\splits.parquet
rows: 26812
row_groups: 1
columns: 5
splits.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "execution_date": {
    "definicion": "Campo 'execution_date' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Corporate Actions - Splits",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_splits",
    "certeza": "oficial+inferencia_local"
  },
  "id": {
    "definicion": "Campo 'id' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Corporate Actions - Splits",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_splits",
    "certeza": "oficial+inferencia_local"
  },
  "split_from": {
    "definicion": "Campo 'split_from' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Corporate Actions - Splits",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_splits",
    "certeza": "oficial+inferencia_local"
  },
  "split_to": {
    "definicion": "Campo 'split_to' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Corporate Actions - Splits",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_splits",
    "certeza": "oficial+inferencia_local"
  },
  "ticker": {
    "definicion": "Simbolo del activo.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Corporate Actions - Splits",
    "mapeo_api": "ticker/sym",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_splits",
    "certeza": "oficial+inferencia_local"
  }
}

**Dividends**
- REST: `reference/dividends`
- Corporate action (dividends).
- local : `C:\TSIS_Data\data\additional\corporate_actions\dividends.parquet` (pendiente/no encontrado)

In [168]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\008_dividends_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\108_dividends_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE NOT FOUND: .

**Economic - Inflation**
- Dataset macroecon?mico auxiliar.
- local : `C:\TSIS_Data\data\additional\economic\inflation.parquet`

In [209]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\010_inflation_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\110_inflation_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\additional\economic\inflation.parquet
rows: 261
row_groups: 1
columns: 7

Schema literal:
date: large_string
cpi: double
cpi_year_over_year: double
cpi_core: double
pce: double
pce_core: double
pce_spending: double

Primeras 5 filas literales:

,date,cpi,cpi_year_over_year,cpi_core,pce,pce_core,pce_spending
0,2004-01-01,186.3,1.926252,194.6,78.909,79.671,8007.1
1,2004-02-01,186.7,1.693064,194.9,79.077,79.800,8040.4
2,2004-03-01,187.1,1.737242,195.5,79.199,79.934,8098.8
3,2004-04-01,187.4,2.285093,195.9,79.346,80.142,8107.2
4,2004-05-01,188.2,3.051771,196.2,79.604,80.252,8176.5

Rango date: 2004-01-01 00:00:00 -> 2025-09-01 00:00:00
FILE: C:\TSIS_Data\data\additional\economic\inflation.parquet
rows: 261
row_groups: 1
columns: 7
inflation.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "date": {
    "definicion": "Fecha asociada al registro.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Economic - Inflation",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  },
  "cpi": {
    "definicion": "Campo 'cpi' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Economic - Inflation",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  },
  "cpi_year_over_year": {
    "definicion": "Campo 'cpi_year_over_year' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Economic - Inflation",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  },
  "cpi_core": {
    "definicion": "Campo 'cpi_core' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Economic - Inflation",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  },
  "pce": {
    "definicion": "Campo 'pce' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Economic - Inflation",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  },
  "pce_core": {
    "definicion": "Campo 'pce_core' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Economic - Inflation",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  },
  "pce_spending": {
    "definicion": "Campo 'pce_spending' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Economic - Inflation",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  }
}

**Economic - Inflation Expectations**
- Dataset macroecon?mico auxiliar.
- local : `C:\TSIS_Data\data\additional\economic\inflation_expectations.parquet`

In [248]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\011_inflation_expectations_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\111_inflation_expectations_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\additional\economic\inflation_expectations.parquet
rows: 262
row_groups: 1
columns: 8

Schema literal:
date: large_string
market_5_year: double
market_10_year: double
forward_years_5_to_10: double
model_1_year: double
model_5_year: double
model_10_year: double
model_30_year: double

Primeras 5 filas literales:

,date,market_5_year,market_10_year,forward_years_5_to_10,model_1_year,model_5_year,model_10_year,model_30_year
0,2004-01-01,2.03,2.26,2.49,1.906971,2.182070,2.316750,2.567783
1,2004-02-01,2.21,2.32,2.43,1.987194,2.150390,2.275457,2.536252
2,2004-03-01,2.27,2.36,2.45,1.704284,2.021547,2.171686,2.474126
3,2004-04-01,2.37,2.45,2.53,1.852767,2.014390,2.148077,2.452269
4,2004-05-01,2.51,2.63,2.75,2.214103,2.346638,2.454690,2.652680

Rango date: 2004-01-01 00:00:00 -> 2025-10-01 00:00:00
FILE: C:\TSIS_Data\data\additional\economic\inflation_expectations.parquet
rows: 262
row_groups: 1
columns: 8
inflation_expectations.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "date": {
    "definicion": "Fecha asociada al registro.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Economic - Inflation Expectations",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  },
  "market_5_year": {
    "definicion": "Campo 'market_5_year' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Economic - Inflation Expectations",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  },
  "market_10_year": {
    "definicion": "Campo 'market_10_year' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Economic - Inflation Expectations",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  },
  "forward_years_5_to_10": {
    "definicion": "Campo 'forward_years_5_to_10' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Economic - Inflation Expectations",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  },
  "model_1_year": {
    "definicion": "Campo 'model_1_year' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Economic - Inflation Expectations",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  },
  "model_5_year": {
    "definicion": "Campo 'model_5_year' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Economic - Inflation Expectations",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  },
  "model_10_year": {
    "definicion": "Campo 'model_10_year' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Economic - Inflation Expectations",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  },
  "model_30_year": {
    "definicion": "Campo 'model_30_year' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Economic - Inflation Expectations",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  }
}

**Economic - Treasury Yields**
- Dataset macroecon?mico auxiliar.
- local : `C:\TSIS_Data\data\additional\economic\treasury_yields.parquet`

In [285]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\012_treasury_yields_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\112_treasury_yields_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\additional\economic\treasury_yields.parquet
rows: 5476
row_groups: 1
columns: 8

Schema literal:
date: large_string
yield_1_month: double
yield_3_month: double
yield_1_year: double
yield_2_year: double
yield_5_year: double
yield_10_year: double
yield_30_year: double

Primeras 5 filas literales:

,date,yield_1_month,yield_3_month,yield_1_year,yield_2_year,yield_5_year,yield_10_year,yield_30_year
0,2004-01-02,0.88,0.93,1.31,1.94,3.36,4.38,5.30
1,2004-01-05,0.88,0.91,1.35,1.95,3.39,4.41,5.28
2,2004-01-06,0.88,0.91,1.30,1.84,3.26,4.29,5.26
3,2004-01-07,0.88,0.91,1.29,1.84,3.25,4.27,5.22
4,2004-01-08,0.87,0.88,1.29,1.85,3.24,4.27,5.20

Rango date: 2004-01-02 00:00:00 -> 2025-11-20 00:00:00
FILE: C:\TSIS_Data\data\additional\economic\treasury_yields.parquet
rows: 5476
row_groups: 1
columns: 8
treasury_yields.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "date": {
    "definicion": "Fecha asociada al registro.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Economic - Treasury Yields",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  },
  "yield_1_month": {
    "definicion": "Campo 'yield_1_month' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Economic - Treasury Yields",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  },
  "yield_3_month": {
    "definicion": "Campo 'yield_3_month' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Economic - Treasury Yields",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  },
  "yield_1_year": {
    "definicion": "Campo 'yield_1_year' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Economic - Treasury Yields",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  },
  "yield_2_year": {
    "definicion": "Campo 'yield_2_year' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Economic - Treasury Yields",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  },
  "yield_5_year": {
    "definicion": "Campo 'yield_5_year' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Economic - Treasury Yields",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  },
  "yield_10_year": {
    "definicion": "Campo 'yield_10_year' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Economic - Treasury Yields",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  },
  "yield_30_year": {
    "definicion": "Campo 'yield_30_year' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Economic - Treasury Yields",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://massive.com/docs/rest/economy",
    "certeza": "oficial+inferencia_local"
  }
}

**IPOs**
- Dataset auxiliar de IPOs.
- local : `C:\TSIS_Data\data\additional\ipos\all_ipos.parquet`

In [319]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\013_all_ipos_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\113_all_ipos_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\additional\ipos\all_ipos.parquet
rows: 5247
row_groups: 1
columns: 14

Schema literal:
ticker: large_string
name: large_string
listing_date: large_string
ipo_status: large_string
security_type: large_string
primary_exchange: large_string
shares_offered: null
price_range_low: null
price_range_high: null
final_price: double
total_offer_size: double
us_code: large_string
isin: large_string
currency: large_string

Primeras 5 filas literales:

,ticker,name,listing_date,ipo_status,security_type,primary_exchange,shares_offered,price_range_low,price_range_high,final_price,total_offer_size,us_code,isin,currency
0,CUYTY,Colruyt Group N.V.,2008-12-11,history,ADRC,OTCM,None,None,None,0.05,5000000.0,196850101,US1968501015,USD
1,VEMLY,Venture Corporation Limited,2009-01-09,history,ADRC,OTCM,None,None,None,0.05,5000000.0,92326A101,US92326A1016,USD
2,YELGY,Hibu Plc,2009-02-10,history,ADRC,OTCM,None,None,None,0.05,5000000.0,42868Y108,US42868Y1082,USD
3,UCBJY,UCB SA,2009-02-10,history,ADRC,OTCM,None,None,None,NaN,NaN,903480101,US9034801012,
4,TTHPY,TT Hellenic Postbank S.A,2009-02-10,history,ADRC,OTCM,None,None,None,0.05,5000000.0,87304Q102,US87304Q1022,USD

Rango listing_date: 2008-12-11 00:00:00 -> 2025-11-28 00:00:00
FILE: C:\TSIS_Data\data\additional\ipos\all_ipos.parquet
rows: 5247
row_groups: 1
columns: 14
all_ipos.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "ticker": {
    "definicion": "Simbolo del activo.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - IPOs",
    "mapeo_api": "ticker/sym",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_vx_reference_ipos",
    "certeza": "oficial+inferencia_local"
  },
  "name": {
    "definicion": "Campo 'name' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - IPOs",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_vx_reference_ipos",
    "certeza": "oficial+inferencia_local"
  },
  "listing_date": {
    "definicion": "Campo 'listing_date' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - IPOs",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_vx_reference_ipos",
    "certeza": "oficial+inferencia_local"
  },
  "ipo_status": {
    "definicion": "Campo 'ipo_status' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - IPOs",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_vx_reference_ipos",
    "certeza": "oficial+inferencia_local"
  },
  "security_type": {
    "definicion": "Campo 'security_type' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - IPOs",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_vx_reference_ipos",
    "certeza": "oficial+inferencia_local"
  },
  "primary_exchange": {
    "definicion": "Campo 'primary_exchange' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - IPOs",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_vx_reference_ipos",
    "certeza": "oficial+inferencia_local"
  },
  "shares_offered": {
    "definicion": "Campo 'shares_offered' presente en este parquet.",
    "tipo_esperado": "null",
    "origen_oficial": "Reference - IPOs",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_vx_reference_ipos",
    "certeza": "oficial+inferencia_local"
  },
  "price_range_low": {
    "definicion": "Campo 'price_range_low' presente en este parquet.",
    "tipo_esperado": "null",
    "origen_oficial": "Reference - IPOs",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_vx_reference_ipos",
    "certeza": "oficial+inferencia_local"
  },
  "price_range_high": {
    "definicion": "Campo 'price_range_high' presente en este parquet.",
    "tipo_esperado": "null",
    "origen_oficial": "Reference - IPOs",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_vx_reference_ipos",
    "certeza": "oficial+inferencia_local"
  },
  "final_price": {
    "definicion": "Campo 'final_price' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Reference - IPOs",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_vx_reference_ipos",
    "certeza": "oficial+inferencia_local"
  },
  "total_offer_size": {
    "definicion": "Campo 'total_offer_size' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Reference - IPOs",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_vx_reference_ipos",
    "certeza": "oficial+inferencia_local"
  },
  "us_code": {
    "definicion": "Campo 'us_code' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - IPOs",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_vx_reference_ipos",
    "certeza": "oficial+inferencia_local"
  },
  "isin": {
    "definicion": "Campo 'isin' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - IPOs",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_vx_reference_ipos",
    "certeza": "oficial+inferencia_local"
  },
  "currency": {
    "definicion": "Campo 'currency' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - IPOs",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_vx_reference_ipos",
    "certeza": "oficial+inferencia_local"
  }
}

**Fundamentals - Balance Sheets**
- REST: `reference/financials` (balance sheets)
- local : `C:\TSIS_Data\data\fundamentals\balance_sheets\{ticker}.parquet`

In [351]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\015_balance_sheets_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\115_balance_sheets_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\fundamentals\balance_sheets\AAC.parquet
rows: 38
row_groups: 1
columns: 33

Schema literal:
tickers: large_list<element: large_string>
  child 0, element: large_string
cik: large_string
period_end: large_string
filing_date: large_string
fiscal_quarter: int64
fiscal_year: int64
timeframe: large_string
cash_and_equivalents: double
receivables: double
other_current_assets: double
total_current_assets: double
property_plant_equipment_net: double
goodwill: double
intangible_assets_net: double
other_assets: double
total_assets: double
accounts_payable: double
debt_current: double
accrued_and_other_current_liabilities: double
total_current_liabilities: double
long_term_debt_and_capital_lease_obligations: double
other_noncurrent_liabilities: double
total_liabilities: double
commitments_and_contingencies: double
common_stock: double
additional_paid_in_capital: double
retained_earnings_deficit: double
other_equity: double
total_equity_attributable_to_parent: double
noncontrolling_interest: double
total_equity: double
total_liabilities_and_equity: double
preferred_stock: double

Primeras 5 filas literales:

,tickers,cik,period_end,filing_date,fiscal_quarter,fiscal_year,timeframe,cash_and_equivalents,receivables,other_current_assets,...,commitments_and_contingencies,common_stock,additional_paid_in_capital,retained_earnings_deficit,other_equity,total_equity_attributable_to_parent,noncontrolling_interest,total_equity,total_liabilities_and_equity,preferred_stock
0,[AAC],0001606180,2014-12-31,2016-03-09,4,2014,quarterly,48540000.0,28718000.0,2664000.0,...,7848000.0,21000.0,88238000.0,9215000.0,0.0,97474000.0,-2333000.0,95141000.0,145952000.0,NaN
1,[AAC],0001606180,2014-12-31,2016-03-09,4,2014,annual,48540000.0,28718000.0,2664000.0,...,7848000.0,21000.0,88238000.0,9215000.0,0.0,97474000.0,-2333000.0,95141000.0,145952000.0,NaN
2,[AAC],0001606180,2015-03-31,2015-05-05,1,2015,quarterly,59186000.0,37713000.0,2686000.0,...,NaN,21000.0,89871000.0,11253000.0,0.0,101145000.0,-2933000.0,98212000.0,188983000.0,NaN
3,[AAC],0001606180,2015-06-30,2015-08-03,2,2015,quarterly,45021000.0,47336000.0,5309000.0,...,NaN,21000.0,92995000.0,16808000.0,0.0,109824000.0,-3372000.0,106452000.0,210265000.0,NaN
4,[AAC],0001606180,2015-09-30,2015-11-10,3,2015,quarterly,10764000.0,58080000.0,7880000.0,...,NaN,22000.0,120438000.0,19260000.0,0.0,139720000.0,-4080000.0,135640000.0,290911000.0,NaN

Rango period_end: 2014-12-31 00:00:00 -> 2023-06-30 00:00:00
Rango filing_date: 2015-05-05 00:00:00 -> 2023-11-08 00:00:00
FILE: C:\TSIS_Data\data\fundamentals\balance_sheets\AAC.parquet
rows: 38
row_groups: 1
columns: 33
balance_sheets/AAC.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "tickers": {
    "definicion": "Campo 'tickers' presente en este parquet.",
    "tipo_esperado": "large_list<element: large_string>",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "cik": {
    "definicion": "Campo 'cik' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "period_end": {
    "definicion": "Campo 'period_end' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "filing_date": {
    "definicion": "Campo 'filing_date' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "fiscal_quarter": {
    "definicion": "Campo 'fiscal_quarter' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "fiscal_year": {
    "definicion": "Campo 'fiscal_year' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "timeframe": {
    "definicion": "Campo 'timeframe' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "cash_and_equivalents": {
    "definicion": "Campo 'cash_and_equivalents' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "receivables": {
    "definicion": "Campo 'receivables' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "other_current_assets": {
    "definicion": "Campo 'other_current_assets' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "total_current_assets": {
    "definicion": "Campo 'total_current_assets' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "property_plant_equipment_net": {
    "definicion": "Campo 'property_plant_equipment_net' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "goodwill": {
    "definicion": "Campo 'goodwill' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "intangible_assets_net": {
    "definicion": "Campo 'intangible_assets_net' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "other_assets": {
    "definicion": "Campo 'other_assets' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "total_assets": {
    "definicion": "Campo 'total_assets' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "accounts_payable": {
    "definicion": "Campo 'accounts_payable' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "debt_current": {
    "definicion": "Campo 'debt_current' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "accrued_and_other_current_liabilities": {
    "definicion": "Campo 'accrued_and_other_current_liabilities' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "total_current_liabilities": {
    "definicion": "Campo 'total_current_liabilities' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "long_term_debt_and_capital_lease_obligations": {
    "definicion": "Campo 'long_term_debt_and_capital_lease_obligations' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "other_noncurrent_liabilities": {
    "definicion": "Campo 'other_noncurrent_liabilities' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "total_liabilities": {
    "definicion": "Campo 'total_liabilities' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "commitments_and_contingencies": {
    "definicion": "Campo 'commitments_and_contingencies' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "common_stock": {
    "definicion": "Campo 'common_stock' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "additional_paid_in_capital": {
    "definicion": "Campo 'additional_paid_in_capital' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "retained_earnings_deficit": {
    "definicion": "Campo 'retained_earnings_deficit' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "other_equity": {
    "definicion": "Campo 'other_equity' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "total_equity_attributable_to_parent": {
    "definicion": "Campo 'total_equity_attributable_to_parent' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "noncontrolling_interest": {
    "definicion": "Campo 'noncontrolling_interest' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "total_equity": {
    "definicion": "Campo 'total_equity' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "total_liabilities_and_equity": {
    "definicion": "Campo 'total_liabilities_and_equity' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  },
  "preferred_stock": {
    "definicion": "Campo 'preferred_stock' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Balance Sheets",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/balance-sheet",
    "certeza": "oficial+inferencia_local"
  }
}

**Fundamentals - Cash Flow Statements**
- REST: `reference/financials` (cash flow)
- local : `C:\TSIS_Data\data\fundamentals\cash_flow_statements\{ticker}.parquet`

In [381]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\016_cash_flow_statements_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\116_cash_flow_statements_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\fundamentals\cash_flow_statements\AAC.parquet
rows: 65
row_groups: 1
columns: 25

Schema literal:
tickers: large_list<element: large_string>
  child 0, element: large_string
cik: large_string
period_end: large_string
filing_date: large_string
fiscal_quarter: int64
fiscal_year: int64
timeframe: large_string
net_income: double
depreciation_depletion_and_amortization: double
other_operating_activities: double
change_in_other_operating_assets_and_liabilities_net: double
cash_from_operating_activities_continuing_operations: double
net_cash_from_operating_activities: double
purchase_of_property_plant_and_equipment: double
other_investing_activities: double
net_cash_from_investing_activities_continuing_operations: double
net_cash_from_investing_activities: double
short_term_debt_issuances_repayments: double
long_term_debt_issuances_repayments: double
dividends: double
noncontrolling_interests: double
other_financing_activities: double
net_cash_from_financing_activities_continuing_operations: double
net_cash_from_financing_activities: double
change_in_cash_and_equivalents: double

Primeras 5 filas literales:

,tickers,cik,period_end,filing_date,fiscal_quarter,fiscal_year,timeframe,net_income,depreciation_depletion_and_amortization,other_operating_activities,...,net_cash_from_investing_activities_continuing_operations,net_cash_from_investing_activities,short_term_debt_issuances_repayments,long_term_debt_issuances_repayments,dividends,noncontrolling_interests,other_financing_activities,net_cash_from_financing_activities_continuing_operations,net_cash_from_financing_activities,change_in_cash_and_equivalents
0,[AAC],0001606180,2014-12-31,2017-03-07,4,2014,annual,6366000.0,4662000.0,11917000.0,...,-19521000.0,-19521000.0,-12550000.0,1799000.0,-509000.0,-915000.0,70186000.0,58011000.0,58011000.0,46528000.0
1,[AAC],0001606180,2014-12-31,2017-03-07,4,2014,quarterly,3273000.0,1225000.0,3538000.0,...,-4220000.0,-4220000.0,-13050000.0,-4759000.0,-430000.0,0.0,63924000.0,45685000.0,45685000.0,43707000.0
2,[AAC],0001606180,2014-12-31,2017-03-07,4,2014,trailing_twelve_months,6366000.0,4662000.0,11884000.0,...,-19521000.0,-19521000.0,-12550000.0,1799000.0,-430000.0,-915000.0,72127000.0,58011000.0,58011000.0,46528000.0
3,[AAC],0001606180,2015-03-31,2016-05-06,1,2015,trailing_twelve_months,7644000.0,4925000.0,12534000.0,...,-41400000.0,-41400000.0,-13050000.0,43815000.0,-430000.0,0.0,63173000.0,91488000.0,91488000.0,54846000.0
4,[AAC],0001606180,2015-03-31,2016-05-06,1,2015,quarterly,2119000.0,1340000.0,5015000.0,...,-25725000.0,-25725000.0,NaN,47427000.0,0.0,NaN,-8529000.0,38898000.0,38898000.0,10646000.0

Rango period_end: 2014-12-31 00:00:00 -> 2023-06-30 00:00:00
Rango filing_date: 2016-05-06 00:00:00 -> 2023-11-08 00:00:00
FILE: C:\TSIS_Data\data\fundamentals\cash_flow_statements\AAC.parquet
rows: 65
row_groups: 1
columns: 25
cash_flow_statements/AAC.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "tickers": {
    "definicion": "Campo 'tickers' presente en este parquet.",
    "tipo_esperado": "large_list<element: large_string>",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "cik": {
    "definicion": "Campo 'cik' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "period_end": {
    "definicion": "Campo 'period_end' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "filing_date": {
    "definicion": "Campo 'filing_date' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "fiscal_quarter": {
    "definicion": "Campo 'fiscal_quarter' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "fiscal_year": {
    "definicion": "Campo 'fiscal_year' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "timeframe": {
    "definicion": "Campo 'timeframe' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "net_income": {
    "definicion": "Campo 'net_income' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "depreciation_depletion_and_amortization": {
    "definicion": "Campo 'depreciation_depletion_and_amortization' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "other_operating_activities": {
    "definicion": "Campo 'other_operating_activities' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "change_in_other_operating_assets_and_liabilities_net": {
    "definicion": "Campo 'change_in_other_operating_assets_and_liabilities_net' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "cash_from_operating_activities_continuing_operations": {
    "definicion": "Campo 'cash_from_operating_activities_continuing_operations' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "net_cash_from_operating_activities": {
    "definicion": "Campo 'net_cash_from_operating_activities' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "purchase_of_property_plant_and_equipment": {
    "definicion": "Campo 'purchase_of_property_plant_and_equipment' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "other_investing_activities": {
    "definicion": "Campo 'other_investing_activities' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "net_cash_from_investing_activities_continuing_operations": {
    "definicion": "Campo 'net_cash_from_investing_activities_continuing_operations' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "net_cash_from_investing_activities": {
    "definicion": "Campo 'net_cash_from_investing_activities' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "short_term_debt_issuances_repayments": {
    "definicion": "Campo 'short_term_debt_issuances_repayments' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "long_term_debt_issuances_repayments": {
    "definicion": "Campo 'long_term_debt_issuances_repayments' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "dividends": {
    "definicion": "Campo 'dividends' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "noncontrolling_interests": {
    "definicion": "Campo 'noncontrolling_interests' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "other_financing_activities": {
    "definicion": "Campo 'other_financing_activities' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "net_cash_from_financing_activities_continuing_operations": {
    "definicion": "Campo 'net_cash_from_financing_activities_continuing_operations' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "net_cash_from_financing_activities": {
    "definicion": "Campo 'net_cash_from_financing_activities' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  },
  "change_in_cash_and_equivalents": {
    "definicion": "Campo 'change_in_cash_and_equivalents' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Cash Flow Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/cash-flow-statement",
    "certeza": "oficial+inferencia_local"
  }
}

**Fundamentals - Income Statements**
- REST: `reference/financials` (income statements)
- local : `C:\TSIS_Data\data\fundamentals\income_statements\{ticker}.parquet`

In [409]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\017_income_statements_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\117_income_statements_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\fundamentals\income_statements\AAC.parquet
rows: 66
row_groups: 1
columns: 30

Schema literal:
tickers: large_list<element: large_string>
  child 0, element: large_string
cik: large_string
period_end: large_string
filing_date: large_string
fiscal_quarter: int64
fiscal_year: int64
timeframe: large_string
revenue: double
cost_of_revenue: double
gross_profit: double
selling_general_administrative: double
depreciation_depletion_amortization: double
other_operating_expenses: double
total_operating_expenses: double
operating_income: double
interest_expense: double
other_income_expense: double
total_other_income_expense: double
income_before_income_taxes: double
income_taxes: double
consolidated_net_income_loss: double
noncontrolling_interest: double
preferred_stock_dividends_declared: double
net_income_loss_attributable_common_shareholders: double
basic_earnings_per_share: double
diluted_earnings_per_share: double
basic_shares_outstanding: double
diluted_shares_outstanding: double
ebitda: double
interest_income: double

Primeras 5 filas literales:

,tickers,cik,period_end,filing_date,fiscal_quarter,fiscal_year,timeframe,revenue,cost_of_revenue,gross_profit,...,consolidated_net_income_loss,noncontrolling_interest,preferred_stock_dividends_declared,net_income_loss_attributable_common_shareholders,basic_earnings_per_share,diluted_earnings_per_share,basic_shares_outstanding,diluted_shares_outstanding,ebitda,interest_income
0,[AAC],0001606180,2014-12-31,2017-03-07,4,2014,quarterly,37166000.0,0.0,37166000.0,...,3273000.0,81000.0,245000.0,3109000.0,0.16,0.16,16557655.00,16619180.00,4961000.0,NaN
1,[AAC],0001606180,2014-12-31,2017-03-07,4,2014,trailing_twelve_months,132968000.0,0.0,132968000.0,...,6366000.0,1182000.0,693000.0,6855000.0,0.40,0.40,15508574.00,15554686.50,15849000.0,NaN
2,[AAC],0001606180,2014-12-31,2017-03-07,4,2014,annual,132968000.0,0.0,132968000.0,...,6366000.0,1182000.0,693000.0,6855000.0,0.41,0.41,16557655.00,16619180.00,16694000.0,NaN
3,[AAC],0001606180,2015-03-31,2016-05-06,1,2015,trailing_twelve_months,145708000.0,0.0,145708000.0,...,7644000.0,1604000.0,1374000.0,7874000.0,0.43,0.43,17201938.25,17259461.75,19472000.0,NaN
4,[AAC],0001606180,2015-03-31,2016-05-06,1,2015,quarterly,42823000.0,0.0,42823000.0,...,2119000.0,600000.0,681000.0,2038000.0,0.10,0.10,21189385.00,21312788.00,6552000.0,NaN

Rango period_end: 2014-12-31 00:00:00 -> 2023-06-30 00:00:00
Rango filing_date: 2016-05-06 00:00:00 -> 2023-11-08 00:00:00
FILE: C:\TSIS_Data\data\fundamentals\income_statements\AAC.parquet
rows: 66
row_groups: 1
columns: 30
income_statements/AAC.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "tickers": {
    "definicion": "Campo 'tickers' presente en este parquet.",
    "tipo_esperado": "large_list<element: large_string>",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "cik": {
    "definicion": "Campo 'cik' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "period_end": {
    "definicion": "Campo 'period_end' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "filing_date": {
    "definicion": "Campo 'filing_date' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "fiscal_quarter": {
    "definicion": "Campo 'fiscal_quarter' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "fiscal_year": {
    "definicion": "Campo 'fiscal_year' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "timeframe": {
    "definicion": "Campo 'timeframe' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "revenue": {
    "definicion": "Campo 'revenue' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "cost_of_revenue": {
    "definicion": "Campo 'cost_of_revenue' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "gross_profit": {
    "definicion": "Campo 'gross_profit' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "selling_general_administrative": {
    "definicion": "Campo 'selling_general_administrative' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "depreciation_depletion_amortization": {
    "definicion": "Campo 'depreciation_depletion_amortization' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "other_operating_expenses": {
    "definicion": "Campo 'other_operating_expenses' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "total_operating_expenses": {
    "definicion": "Campo 'total_operating_expenses' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "operating_income": {
    "definicion": "Campo 'operating_income' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "interest_expense": {
    "definicion": "Campo 'interest_expense' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "other_income_expense": {
    "definicion": "Campo 'other_income_expense' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "total_other_income_expense": {
    "definicion": "Campo 'total_other_income_expense' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "income_before_income_taxes": {
    "definicion": "Campo 'income_before_income_taxes' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "income_taxes": {
    "definicion": "Campo 'income_taxes' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "consolidated_net_income_loss": {
    "definicion": "Campo 'consolidated_net_income_loss' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "noncontrolling_interest": {
    "definicion": "Campo 'noncontrolling_interest' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "preferred_stock_dividends_declared": {
    "definicion": "Campo 'preferred_stock_dividends_declared' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "net_income_loss_attributable_common_shareholders": {
    "definicion": "Campo 'net_income_loss_attributable_common_shareholders' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "basic_earnings_per_share": {
    "definicion": "Campo 'basic_earnings_per_share' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "diluted_earnings_per_share": {
    "definicion": "Campo 'diluted_earnings_per_share' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "basic_shares_outstanding": {
    "definicion": "Campo 'basic_shares_outstanding' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "diluted_shares_outstanding": {
    "definicion": "Campo 'diluted_shares_outstanding' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "ebitda": {
    "definicion": "Campo 'ebitda' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  },
  "interest_income": {
    "definicion": "Campo 'interest_income' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Income Statements",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/income-statement",
    "certeza": "oficial+inferencia_local"
  }
}

**Fundamentals - Smallcap Ratios**
- Ratios derivados para small/micro caps.
- local : `C:\TSIS_Data\data\fundamentals\smallcap_ratios\{ticker}.parquet`

In [435]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\018_smallcap_ratios_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\118_smallcap_ratios_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\fundamentals\smallcap_ratios\AAC.parquet
rows: 38
row_groups: 1
columns: 19

Schema literal:
ticker: null
fiscal_period: null
fiscal_year: int64
end_date: null
current_ratio: null
quick_ratio: null
cash_ratio: null
quarterly_burn_rate: int64
cash_runway_quarters: null
debt_to_equity: double
debt_to_assets: double
gross_margin: null
operating_margin: null
net_margin: null
roa: double
roe: double
bankruptcy_risk_flag: bool
dilution_risk_flag: bool
high_leverage_flag: bool

Primeras 5 filas literales:

,ticker,fiscal_period,fiscal_year,end_date,current_ratio,quick_ratio,cash_ratio,quarterly_burn_rate,cash_runway_quarters,debt_to_equity,debt_to_assets,gross_margin,operating_margin,net_margin,roa,roe,bankruptcy_risk_flag,dilution_risk_flag,high_leverage_flag
0,None,None,2014,None,None,None,None,0,None,0.0,0.0,None,None,None,0.0,0.0,False,False,False
1,None,None,2014,None,None,None,None,0,None,0.0,0.0,None,None,None,0.0,0.0,False,False,False
2,None,None,2015,None,None,None,None,0,None,0.0,0.0,None,None,None,0.0,0.0,False,False,False
3,None,None,2015,None,None,None,None,0,None,0.0,0.0,None,None,None,0.0,0.0,False,False,False
4,None,None,2015,None,None,None,None,0,None,0.0,0.0,None,None,None,0.0,0.0,False,False,False

FILE: C:\TSIS_Data\data\fundamentals\smallcap_ratios\AAC.parquet
rows: 38
row_groups: 1
columns: 19
smallcap_ratios/AAC.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "ticker": {
    "definicion": "Simbolo del activo.",
    "tipo_esperado": "null",
    "origen_oficial": "Fundamentals - Ratios",
    "mapeo_api": "ticker/sym",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/ratios",
    "certeza": "oficial+inferencia_local"
  },
  "fiscal_period": {
    "definicion": "Campo 'fiscal_period' presente en este parquet.",
    "tipo_esperado": "null",
    "origen_oficial": "Fundamentals - Ratios",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/ratios",
    "certeza": "oficial+inferencia_local"
  },
  "fiscal_year": {
    "definicion": "Campo 'fiscal_year' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Fundamentals - Ratios",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/ratios",
    "certeza": "oficial+inferencia_local"
  },
  "end_date": {
    "definicion": "Campo 'end_date' presente en este parquet.",
    "tipo_esperado": "null",
    "origen_oficial": "Fundamentals - Ratios",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/ratios",
    "certeza": "oficial+inferencia_local"
  },
  "current_ratio": {
    "definicion": "Campo 'current_ratio' presente en este parquet.",
    "tipo_esperado": "null",
    "origen_oficial": "Fundamentals - Ratios",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/ratios",
    "certeza": "oficial+inferencia_local"
  },
  "quick_ratio": {
    "definicion": "Campo 'quick_ratio' presente en este parquet.",
    "tipo_esperado": "null",
    "origen_oficial": "Fundamentals - Ratios",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/ratios",
    "certeza": "oficial+inferencia_local"
  },
  "cash_ratio": {
    "definicion": "Campo 'cash_ratio' presente en este parquet.",
    "tipo_esperado": "null",
    "origen_oficial": "Fundamentals - Ratios",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/ratios",
    "certeza": "oficial+inferencia_local"
  },
  "quarterly_burn_rate": {
    "definicion": "Campo 'quarterly_burn_rate' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Fundamentals - Ratios",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/ratios",
    "certeza": "oficial+inferencia_local"
  },
  "cash_runway_quarters": {
    "definicion": "Campo 'cash_runway_quarters' presente en este parquet.",
    "tipo_esperado": "null",
    "origen_oficial": "Fundamentals - Ratios",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/ratios",
    "certeza": "oficial+inferencia_local"
  },
  "debt_to_equity": {
    "definicion": "Campo 'debt_to_equity' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Ratios",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/ratios",
    "certeza": "oficial+inferencia_local"
  },
  "debt_to_assets": {
    "definicion": "Campo 'debt_to_assets' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Ratios",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/ratios",
    "certeza": "oficial+inferencia_local"
  },
  "gross_margin": {
    "definicion": "Campo 'gross_margin' presente en este parquet.",
    "tipo_esperado": "null",
    "origen_oficial": "Fundamentals - Ratios",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/ratios",
    "certeza": "oficial+inferencia_local"
  },
  "operating_margin": {
    "definicion": "Campo 'operating_margin' presente en este parquet.",
    "tipo_esperado": "null",
    "origen_oficial": "Fundamentals - Ratios",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/ratios",
    "certeza": "oficial+inferencia_local"
  },
  "net_margin": {
    "definicion": "Campo 'net_margin' presente en este parquet.",
    "tipo_esperado": "null",
    "origen_oficial": "Fundamentals - Ratios",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/ratios",
    "certeza": "oficial+inferencia_local"
  },
  "roa": {
    "definicion": "Campo 'roa' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Ratios",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/ratios",
    "certeza": "oficial+inferencia_local"
  },
  "roe": {
    "definicion": "Campo 'roe' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Fundamentals - Ratios",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/ratios",
    "certeza": "oficial+inferencia_local"
  },
  "bankruptcy_risk_flag": {
    "definicion": "Campo 'bankruptcy_risk_flag' presente en este parquet.",
    "tipo_esperado": "bool",
    "origen_oficial": "Fundamentals - Ratios",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/ratios",
    "certeza": "oficial+inferencia_local"
  },
  "dilution_risk_flag": {
    "definicion": "Campo 'dilution_risk_flag' presente en este parquet.",
    "tipo_esperado": "bool",
    "origen_oficial": "Fundamentals - Ratios",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/ratios",
    "certeza": "oficial+inferencia_local"
  },
  "high_leverage_flag": {
    "definicion": "Campo 'high_leverage_flag' presente en este parquet.",
    "tipo_esperado": "bool",
    "origen_oficial": "Fundamentals - Ratios",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/rest/stocks/fundamentals/ratios",
    "certeza": "oficial+inferencia_local"
  }
}

**Fundamentals - Financial Ratios**
- REST/derivado de financial ratios.
- local : `C:\TSIS_Data\data\fundamentals\financial_ratios\{ticker}.parquet`

In [459]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\019_financial_ratios_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\119_financial_ratios_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE NOT FOUND: C:\TSIS_Data\data\fundamentals\financial_ratios\AAC.parquet
FILE NOT FOUND: C:\TSIS_Data\data\fundamentals\financial_ratios\AAC.parquet

**News**
- REST: `stocks/news`
- Noticias de stocks en batches.
- local : `C:\TSIS_Data\data\additional\news\news_batch_0000.parquet`

In [481]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\014_news_batch_0000_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\114_news_batch_0000_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\additional\news\news_batch_0000.parquet
rows: 5244
row_groups: 1
columns: 9

Schema literal:
ticker: large_string
article_id: large_string
title: large_string
description: large_string
published_utc: large_string
article_url: large_string
publisher_name: large_string
tickers_mentioned: large_string
keywords: large_string

Primeras 5 filas literales:

,ticker,article_id,title,description,published_utc,article_url,publisher_name,tickers_mentioned,keywords
0,AAC,w0gNOyy5_8Y1fNONHgY6PLIcl8b3dciHKQZikHM-KgU,Rush Street Interactive: Asymmetric Risk Reward,Rush Street Interactive trades at a massive di...,2021-07-27T04:15:14Z,https://seekingalpha.com/article/4441521-rush-...,Seeking Alpha,"AAC,DKNG,GNOG,RSI",
1,AAC,Smyr2slA3_dn9xteXiYvCSX6MCYZ4MiAMbzKLwft0B4,Ares debuts second SPAC IPO in uncertain times...,Ares upsizes Ares Acquisition Corp. II SPAC bu...,2023-04-28T18:28:00Z,https://www.marketwatch.com/story/ares-debuts-...,MarketWatch,"ARES,ARCC,ACRE,ARDC,AAC,C,UBS,KKR,GS",
2,AAC,XfnC3ZtdAMdoSkLlJLOXKu9mpJ8Fgr4QQShZpCL4bwQ,British billionaire owner of Tottenham footbal...,Joe Lewis is accused by U.S. authorities of sh...,2023-07-26T01:12:00Z,https://www.marketwatch.com/story/british-bill...,MarketWatch,"SLDB,MRTX,AAC",
3,AAC,4gj0JxFOlJydx8hJ5QkNJBf7vC6-RqjNDnTVQxmcMPQ,Why X-Energy Partner Ares Acquisition Stock Po...,This nuclear power SPAC IPO is now dead as a d...,2023-10-31T15:06:36Z,https://www.fool.com/investing/2023/10/31/why-...,The Motley Fool,AAC,investing
4,AAC,k1YIxazi0j-DhXhJrVEgaaVzj0oeogtpQgSSR0my4dg,"Ares Acquisition Corp., X-energy scrap $1.8B m...",The deal marks the 165th SPACs that has liquid...,2023-10-31T18:20:00Z,https://www.marketwatch.com/story/ares-acquisi...,MarketWatch,"AAC,ARES,NETD,AACT,GHIX",

Rango published_utc: 2020-04-07 13:15:00+00:00 -> 2025-11-19 18:00:00+00:00
FILE: C:\TSIS_Data\data\additional\news\news_batch_0000.parquet
rows: 5244
row_groups: 1
columns: 9
news_batch_0000.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "ticker": {
    "definicion": "Simbolo del activo.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "ticker/sym",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "article_id": {
    "definicion": "Campo 'article_id' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "title": {
    "definicion": "Campo 'title' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "description": {
    "definicion": "Campo 'description' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "published_utc": {
    "definicion": "Campo 'published_utc' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "article_url": {
    "definicion": "Campo 'article_url' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "publisher_name": {
    "definicion": "Campo 'publisher_name' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "tickers_mentioned": {
    "definicion": "Campo 'tickers_mentioned' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "keywords": {
    "definicion": "Campo 'keywords' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  }
}

**News**
- REST: `stocks/news`
- Noticias de stocks en batches.
- local : `C:\TSIS_Data\data\additional\news\news_batch_0001.parquet`

In [501]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\027_news_batch_0001_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\127_news_batch_0001_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\additional\news\news_batch_0001.parquet
rows: 4262
row_groups: 1
columns: 9

Schema literal:
ticker: large_string
article_id: large_string
title: large_string
description: large_string
published_utc: large_string
article_url: large_string
publisher_name: large_string
tickers_mentioned: large_string
keywords: large_string

Primeras 5 filas literales:

,ticker,article_id,title,description,published_utc,article_url,publisher_name,tickers_mentioned,keywords
0,ACRE,YiIgjoku4Cgyq2AY6T2ocytqyitF1sr5-axA1qgrPvg,Ares Commercial Real Estate (ACRE) Q1 Earnings...,Ares Commercial Real Estate (ACRE) delivered e...,2021-05-04T11:35:02Z,http://www.zacks.com/stock/news/1498219/ares-c...,Zacks Investment Research,ACRE,
1,ACRE,BIUARkqvkvdwr79g4kmyuIeMhLBzgGf664P3Edkf1ck,Shortages Of Everything,Real estate equities were mixed amid the busie...,2021-05-08T17:00:00Z,https://seekingalpha.com/article/4425948-short...,Seeking Alpha,"EQC,MNR,AMH,CPLG,APLE,PEB,HST,PK,REG,BRX,FRT,R...",
2,ACRE,g8VqVC5yZgfkzjYDjEG1lSatEbos4ERw59wgyZuKuTI,Stocks That Hit 52-Week Highs On Monday,This morning 792 companies reached new 52-week...,2021-05-10T15:26:09Z,https://www.benzinga.com/news/21/05/21035954/s...,Benzinga,"JACK,RGP,HLIO,NVO,EQT,UFS,VBTX,UFPT,VLRS,KB,BH...","News,Penny Stocks,Small Cap,Intraday Update,Ma..."
3,ACRE,Mgz053uF-yE_ZwBmC6qNhwNp8V275v6W8IOB0Kpj7co,Stocks That Hit 52-Week Highs On Tuesday,Tuesday's morning session saw 173 companies se...,2021-05-25T14:52:48Z,https://www.benzinga.com/news/21/05/21280254/s...,Benzinga,"EPAM,PSEC,VRT,MTX,CET,PGNY,DKL,C,SWZ,EPIX,PRAH...","News,Intraday Update,Markets,Movers,Trading Ideas"
4,ACRE,J4bEDIiI_fa9b396KS1_8rR_22svHPsM7TJ2emBNHw8,Rents Are Surging Again,Driven by an intensifying housing shortage as ...,2021-05-29T18:00:00Z,https://seekingalpha.com/article/4432051-rents...,Seeking Alpha,"AAIC,AAT,ABR,ACC,ACR,ACRE,ADC,AFCG,AFIN,AFINO,...",

Rango published_utc: 2020-12-04 14:15:00+00:00 -> 2025-11-23 15:18:01+00:00
FILE: C:\TSIS_Data\data\additional\news\news_batch_0001.parquet
rows: 4262
row_groups: 1
columns: 9
news_batch_0001.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "ticker": {
    "definicion": "Simbolo del activo.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "ticker/sym",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "article_id": {
    "definicion": "Campo 'article_id' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "title": {
    "definicion": "Campo 'title' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "description": {
    "definicion": "Campo 'description' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "published_utc": {
    "definicion": "Campo 'published_utc' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "article_url": {
    "definicion": "Campo 'article_url' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "publisher_name": {
    "definicion": "Campo 'publisher_name' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "tickers_mentioned": {
    "definicion": "Campo 'tickers_mentioned' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "keywords": {
    "definicion": "Campo 'keywords' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  }
}

**News**
- REST: `stocks/news`
- Noticias de stocks en batches.
- local : `C:\TSIS_Data\data\additional\news\news_batch_0002.parquet`

In [519]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\028_news_batch_0002_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\128_news_batch_0002_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\additional\news\news_batch_0002.parquet
rows: 4698
row_groups: 1
columns: 9

Schema literal:
ticker: large_string
article_id: large_string
title: large_string
description: large_string
published_utc: large_string
article_url: large_string
publisher_name: large_string
tickers_mentioned: large_string
keywords: large_string

Primeras 5 filas literales:

,ticker,article_id,title,description,published_utc,article_url,publisher_name,tickers_mentioned,keywords
0,AGCB,9UwjFxZeCYeDr2CEFjSQS5ZnqoxsxEOiE0DZSJq4qZk,Tracking Seth Klarman's Baupost Group Holdings...,Seth Klarman’s 13F portfolio value increased f...,2021-05-20T06:36:04Z,https://seekingalpha.com/article/4430095-track...,Seeking Alpha,"ADV,AGCB,AJAX,AON,ATRA,AVAN,BSN,CGEM,CLNY,DGNS...",
1,AGCB,q4r4R2mgkEK_dpVwzkKemFMseOYswefinVKXbghprM0,Tracking Seth Klarman's Baupost Group Holdings...,Seth Klarman’s 13F portfolio value decreased f...,2022-02-15T08:36:25Z,https://seekingalpha.com/article/4486983-track...,Seeking Alpha,"ADV,AGCB,ATRA,AUR,AUROW,AVAN,AVAN.U,CVT,DBRG,D...",
2,AGCB,nxvHHSComnwxyBhLwle1B43eSu_jp91V3sDLeSaWpw4,Tracking David Tepper's Appaloosa Management P...,David Tepper's 13F portfolio value decreased f...,2022-05-27T06:39:36Z,https://seekingalpha.com/article/4514907-track...,Seeking Alpha,"AGCB,ALIT,AMLP,AMZN,APA,AR,CHK,DHI,DKS,EPD,EQT...",
3,AGEN,IQ-vQBXo6Ap5r7y_1BPG4u5oIsaFzacg0eAVJWZUraY,"Agenus (AGEN) Reports Q1 Loss, Misses Revenue ...",Agenus (AGEN) delivered earnings and revenue s...,2021-05-06T12:55:07Z,http://www.zacks.com/stock/news/1509705/agenus...,Zacks Investment Research,AGEN,
4,AGEN,v6_UrU583BZHYmuDeXKX1rSP7-HdZzKruzIvREztvXw,Agenus Inc (AGEN) Q1 2021 Earnings Call Transc...,AGEN earnings call for the period ending April...,2021-05-06T19:30:46Z,https://www.fool.com/earnings/call-transcripts...,The Motley Fool,AGEN,earningscall-transcripts

Rango published_utc: 2020-05-22 13:15:00+00:00 -> 2025-11-20 19:53:00+00:00
FILE: C:\TSIS_Data\data\additional\news\news_batch_0002.parquet
rows: 4698
row_groups: 1
columns: 9
news_batch_0002.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "ticker": {
    "definicion": "Simbolo del activo.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "ticker/sym",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "article_id": {
    "definicion": "Campo 'article_id' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "title": {
    "definicion": "Campo 'title' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "description": {
    "definicion": "Campo 'description' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "published_utc": {
    "definicion": "Campo 'published_utc' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "article_url": {
    "definicion": "Campo 'article_url' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "publisher_name": {
    "definicion": "Campo 'publisher_name' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "tickers_mentioned": {
    "definicion": "Campo 'tickers_mentioned' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  },
  "keywords": {
    "definicion": "Campo 'keywords' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "News - Stocks News",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v2_reference_news",
    "certeza": "oficial+inferencia_local"
  }
}

**Technical Indicators (local sample)**
- Exploraci?n de indicadores/r?gimen local.
- local : `C:\TSIS_Data\data\regime_indicators\...\*.parquet`

In [535]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\029_regime_indicators_sample_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\129_regime_indicators_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\regime_indicators\etfs\DIA\day.parquet
rows: 5593
row_groups: 1
columns: 9

Schema literal:
volume: double
vwap: double
open: double
close: double
high: double
low: double
trades: int64
datetime: timestamp[us]
date: date32[day]

Primeras 5 filas literales:

,volume,vwap,open,close,high,low,trades,datetime,date
0,7632800.0,94.7619,95.09,94.68,95.25,94.21,8310,1970-01-01 00:17:43.166400,1970-01-01
1,6202300.0,94.9356,94.74,94.97,95.34,94.53,6652,1970-01-01 00:17:43.252800,1970-01-01
2,5045800.0,94.6200,94.55,95.05,95.20,94.10,6355,1970-01-01 00:17:43.339200,1970-01-01
3,3837800.0,94.9655,95.13,94.83,95.21,94.25,5440,1970-01-01 00:17:43.598400,1970-01-01
4,4996700.0,95.3914,94.95,96.00,96.05,94.91,5894,1970-01-01 00:17:43.684800,1970-01-01

Rango date: 1970-01-01 00:00:00 -> 1970-01-01 00:00:00
Rango datetime: 1970-01-01 00:17:43.166400 -> 1970-01-01 00:29:24.565200
FILE: C:\TSIS_Data\data\regime_indicators\etfs\DIA\day.parquet
rows: 5593
row_groups: 1
columns: 9
regime_indicators sample

Diccionario tecnico de variables (oficial + mapeo local):
{
  "volume": {
    "definicion": "Volumen agregado en la ventana temporal.",
    "tipo_esperado": "double",
    "origen_oficial": "Regime Indicators (local derivado)",
    "mapeo_api": "v",
    "nota_local": "Dataset derivado local; no mapeo 1:1 oficial para todas las columnas.",
    "source_url": "N/A",
    "certeza": "inferido_local"
  },
  "vwap": {
    "definicion": "Precio medio ponderado por volumen.",
    "tipo_esperado": "double",
    "origen_oficial": "Regime Indicators (local derivado)",
    "mapeo_api": "vw",
    "nota_local": "Dataset derivado local; no mapeo 1:1 oficial para todas las columnas.",
    "source_url": "N/A",
    "certeza": "inferido_local"
  },
  "open": {
    "definicion": "Precio de apertura de la ventana.",
    "tipo_esperado": "double",
    "origen_oficial": "Regime Indicators (local derivado)",
    "mapeo_api": "o",
    "nota_local": "Dataset derivado local; no mapeo 1:1 oficial para todas las columnas.",
    "source_url": "N/A",
    "certeza": "inferido_local"
  },
  "close": {
    "definicion": "Precio de cierre de la ventana.",
    "tipo_esperado": "double",
    "origen_oficial": "Regime Indicators (local derivado)",
    "mapeo_api": "c",
    "nota_local": "Dataset derivado local; no mapeo 1:1 oficial para todas las columnas.",
    "source_url": "N/A",
    "certeza": "inferido_local"
  },
  "high": {
    "definicion": "Precio maximo de la ventana.",
    "tipo_esperado": "double",
    "origen_oficial": "Regime Indicators (local derivado)",
    "mapeo_api": "h",
    "nota_local": "Dataset derivado local; no mapeo 1:1 oficial para todas las columnas.",
    "source_url": "N/A",
    "certeza": "inferido_local"
  },
  "low": {
    "definicion": "Precio minimo de la ventana.",
    "tipo_esperado": "double",
    "origen_oficial": "Regime Indicators (local derivado)",
    "mapeo_api": "l",
    "nota_local": "Dataset derivado local; no mapeo 1:1 oficial para todas las columnas.",
    "source_url": "N/A",
    "certeza": "inferido_local"
  },
  "trades": {
    "definicion": "Campo 'trades' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Regime Indicators (local derivado)",
    "mapeo_api": "N/A",
    "nota_local": "Dataset derivado local; no mapeo 1:1 oficial para todas las columnas.",
    "source_url": "N/A",
    "certeza": "inferido_local"
  },
  "datetime": {
    "definicion": "Fecha-hora del registro.",
    "tipo_esperado": "timestamp[us]",
    "origen_oficial": "Regime Indicators (local derivado)",
    "mapeo_api": "N/A",
    "nota_local": "Dataset derivado local; no mapeo 1:1 oficial para todas las columnas.",
    "source_url": "N/A",
    "certeza": "inferido_local"
  },
  "date": {
    "definicion": "Fecha del registro.",
    "tipo_esperado": "date32[day]",
    "origen_oficial": "Regime Indicators (local derivado)",
    "mapeo_api": "N/A",
    "nota_local": "Dataset derivado local; no mapeo 1:1 oficial para todas las columnas.",
    "source_url": "N/A",
    "certeza": "inferido_local"
  }
}

**Short Data - Short Interest**
- Dataset de short interest.
- local : `C:\TSIS_Data\data\short_data\short_interest\{ticker}.parquet`

In [549]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\020_short_interest_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\120_short_interest_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\short_data\short_interest\AABA.parquet
rows: 43
row_groups: 1
columns: 5

Schema literal:
settlement_date: large_string
ticker: large_string
short_interest: int64
avg_daily_volume: int64
days_to_cover: double

Primeras 5 filas literales:

  settlement_date ticker  short_interest  avg_daily_volume  days_to_cover
0      2017-12-29   AABA        23472187           9376655           2.50
1      2018-01-12   AABA        23750001           7991624           2.97
2      2018-01-31   AABA        28308876           8208679           3.45
3      2018-02-15   AABA        25431892           6378598           3.99
4      2018-02-28   AABA        24351969          10558499           2.31

Rango settlement_date: 2017-12-29 00:00:00 -> 2019-09-30 00:00:00
FILE: C:\TSIS_Data\data\short_data\short_interest\AABA.parquet
rows: 43
row_groups: 1
columns: 5
short_interest/AABA.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "settlement_date": {
    "definicion": "Campo 'settlement_date' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Short Data - Short Interest",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_interest",
    "certeza": "oficial+inferencia_local"
  },
  "ticker": {
    "definicion": "Simbolo del activo.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Short Data - Short Interest",
    "mapeo_api": "ticker/sym",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_interest",
    "certeza": "oficial+inferencia_local"
  },
  "short_interest": {
    "definicion": "Campo 'short_interest' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Short Data - Short Interest",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_interest",
    "certeza": "oficial+inferencia_local"
  },
  "avg_daily_volume": {
    "definicion": "Campo 'avg_daily_volume' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Short Data - Short Interest",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_interest",
    "certeza": "oficial+inferencia_local"
  },
  "days_to_cover": {
    "definicion": "Campo 'days_to_cover' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Short Data - Short Interest",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_interest",
    "certeza": "oficial+inferencia_local"
  }
}

**Short Data - Short Volume**
- Dataset de short volume.
- local : `C:\TSIS_Data\data\short_data\short_volume\{ticker}.parquet`

In [561]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\021_short_volume_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\121_short_volume_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\short_data\short_volume\AACB.parquet
rows: 109
row_groups: 1
columns: 20

Schema literal:
ticker: large_string
date: large_string
total_volume: int64
short_volume: int64
exempt_volume: int64
non_exempt_volume: int64
short_volume_ratio: double
nyse_short_volume: int64
nyse_short_volume_exempt: int64
nasdaq_carteret_short_volume: int64
nasdaq_carteret_short_volume_exempt: int64
nasdaq_chicago_short_volume: int64
nasdaq_chicago_short_volume_exempt: int64
adf_short_volume: int64
adf_short_volume_exempt: int64
short_ratio: double
exempt_ratio: int32
short_ratio_ma5: double
short_ratio_change: double
short_ratio_zscore: double

Primeras 5 filas literales:

,ticker,date,total_volume,short_volume,exempt_volume,non_exempt_volume,short_volume_ratio,nyse_short_volume,nyse_short_volume_exempt,nasdaq_carteret_short_volume,nasdaq_carteret_short_volume_exempt,nasdaq_chicago_short_volume,nasdaq_chicago_short_volume_exempt,adf_short_volume,adf_short_volume_exempt,short_ratio,exempt_ratio,short_ratio_ma5,short_ratio_change,short_ratio_zscore
0,AACB,2025-04-07,2061,231,0,231,11.21,1,0,230,0,0,0,0,0,0.112082,0,NaN,NaN,NaN
1,AACB,2025-04-08,2,2,0,2,100.00,0,0,2,0,0,0,0,0,1.000000,0,NaN,0.887918,NaN
2,AACB,2025-04-09,2,2,0,2,100.00,2,0,0,0,0,0,0,0,1.000000,0,NaN,0.000000,NaN
3,AACB,2025-04-10,100811,781,0,781,0.77,0,0,781,0,0,0,0,0,0.007747,0,NaN,-0.992253,NaN
4,AACB,2025-04-11,636467,2304,0,2304,0.36,0,0,2304,0,0,0,0,0,0.003620,0,0.42469,-0.004127,NaN

Rango date: 2025-04-07 00:00:00 -> 2025-11-21 00:00:00
FILE: C:\TSIS_Data\data\short_data\short_volume\AACB.parquet
rows: 109
row_groups: 1
columns: 20
short_volume/AACB.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "ticker": {
    "definicion": "Simbolo del activo.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Short Data - Short Volume",
    "mapeo_api": "ticker/sym",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_volume",
    "certeza": "oficial+inferencia_local"
  },
  "date": {
    "definicion": "Fecha asociada al registro.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Short Data - Short Volume",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_volume",
    "certeza": "oficial+inferencia_local"
  },
  "total_volume": {
    "definicion": "Campo 'total_volume' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Short Data - Short Volume",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_volume",
    "certeza": "oficial+inferencia_local"
  },
  "short_volume": {
    "definicion": "Campo 'short_volume' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Short Data - Short Volume",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_volume",
    "certeza": "oficial+inferencia_local"
  },
  "exempt_volume": {
    "definicion": "Campo 'exempt_volume' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Short Data - Short Volume",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_volume",
    "certeza": "oficial+inferencia_local"
  },
  "non_exempt_volume": {
    "definicion": "Campo 'non_exempt_volume' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Short Data - Short Volume",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_volume",
    "certeza": "oficial+inferencia_local"
  },
  "short_volume_ratio": {
    "definicion": "Campo 'short_volume_ratio' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Short Data - Short Volume",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_volume",
    "certeza": "oficial+inferencia_local"
  },
  "nyse_short_volume": {
    "definicion": "Campo 'nyse_short_volume' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Short Data - Short Volume",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_volume",
    "certeza": "oficial+inferencia_local"
  },
  "nyse_short_volume_exempt": {
    "definicion": "Campo 'nyse_short_volume_exempt' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Short Data - Short Volume",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_volume",
    "certeza": "oficial+inferencia_local"
  },
  "nasdaq_carteret_short_volume": {
    "definicion": "Campo 'nasdaq_carteret_short_volume' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Short Data - Short Volume",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_volume",
    "certeza": "oficial+inferencia_local"
  },
  "nasdaq_carteret_short_volume_exempt": {
    "definicion": "Campo 'nasdaq_carteret_short_volume_exempt' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Short Data - Short Volume",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_volume",
    "certeza": "oficial+inferencia_local"
  },
  "nasdaq_chicago_short_volume": {
    "definicion": "Campo 'nasdaq_chicago_short_volume' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Short Data - Short Volume",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_volume",
    "certeza": "oficial+inferencia_local"
  },
  "nasdaq_chicago_short_volume_exempt": {
    "definicion": "Campo 'nasdaq_chicago_short_volume_exempt' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Short Data - Short Volume",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_volume",
    "certeza": "oficial+inferencia_local"
  },
  "adf_short_volume": {
    "definicion": "Campo 'adf_short_volume' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Short Data - Short Volume",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_volume",
    "certeza": "oficial+inferencia_local"
  },
  "adf_short_volume_exempt": {
    "definicion": "Campo 'adf_short_volume_exempt' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Short Data - Short Volume",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_volume",
    "certeza": "oficial+inferencia_local"
  },
  "short_ratio": {
    "definicion": "Campo 'short_ratio' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Short Data - Short Volume",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_volume",
    "certeza": "oficial+inferencia_local"
  },
  "exempt_ratio": {
    "definicion": "Campo 'exempt_ratio' presente en este parquet.",
    "tipo_esperado": "int32",
    "origen_oficial": "Short Data - Short Volume",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_volume",
    "certeza": "oficial+inferencia_local"
  },
  "short_ratio_ma5": {
    "definicion": "Campo 'short_ratio_ma5' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Short Data - Short Volume",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_volume",
    "certeza": "oficial+inferencia_local"
  },
  "short_ratio_change": {
    "definicion": "Campo 'short_ratio_change' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Short Data - Short Volume",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_volume",
    "certeza": "oficial+inferencia_local"
  },
  "short_ratio_zscore": {
    "definicion": "Campo 'short_ratio_zscore' presente en este parquet.",
    "tipo_esperado": "double",
    "origen_oficial": "Short Data - Short Volume",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker__short_volume",
    "certeza": "oficial+inferencia_local"
  }
}

**Reference - Condition Codes**
- C?digos de condici?n de mercado.
- local : `C:\TSIS_Data\data\reference\condition_codes.parquet`

In [571]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\022_reference_condition_codes_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\122_reference_condition_codes_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\reference\condition_codes.parquet
rows: 10
row_groups: 1
columns: 15

Schema literal:
id: int64
type: large_string
name: large_string
asset_class: large_string
sip_mapping: struct<CTA: large_string, UTP: large_string, FINRA_TDDS: large_string>
  child 0, CTA: large_string
  child 1, UTP: large_string
  child 2, FINRA_TDDS: large_string
update_rules: struct<consolidated: struct<updates_high_low: bool, updates_open_close: bool, updates_volume: bool>, (... 95 chars omitted)
  child 0, consolidated: struct<updates_high_low: bool, updates_open_close: bool, updates_volume: bool>
      child 0, updates_high_low: bool
      child 1, updates_open_close: bool
      child 2, updates_volume: bool
  child 1, market_center: struct<updates_high_low: bool, updates_open_close: bool, updates_volume: bool>
      child 0, updates_high_low: bool
      child 1, updates_open_close: bool
      child 2, updates_volume: bool
data_types: large_list<element: large_string>
  child 0, element: large_string
legacy: bool

Primeras 5 filas literales:

,id,type,name,asset_class,sip_mapping,update_rules,data_types,legacy
0,1,sale_condition,Acquisition,stocks,"{'CTA': None, 'UTP': 'A', 'FINRA_TDDS': None}","{'consolidated': {'updates_high_low': True, 'u...",[trade],None
1,2,sale_condition,Average Price Trade,stocks,"{'CTA': 'B', 'UTP': 'W', 'FINRA_TDDS': 'W'}","{'consolidated': {'updates_high_low': False, '...",[trade],None
2,3,sale_condition,Automatic Execution,stocks,"{'CTA': 'E', 'UTP': None, 'FINRA_TDDS': None}","{'consolidated': {'updates_high_low': True, 'u...",[trade],None
3,4,sale_condition,Bunched Trade,stocks,"{'CTA': None, 'UTP': 'B', 'FINRA_TDDS': None}","{'consolidated': {'updates_high_low': True, 'u...",[trade],None
4,5,sale_condition,Bunched Sold Trade,stocks,"{'CTA': None, 'UTP': 'G', 'FINRA_TDDS': None}","{'consolidated': {'updates_high_low': True, 'u...",[trade],None

FILE: C:\TSIS_Data\data\reference\condition_codes.parquet
rows: 10
row_groups: 1
columns: 15
reference/condition_codes.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "id": {
    "definicion": "Campo 'id' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Reference - Condition Codes",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_conditions",
    "certeza": "oficial+inferencia_local"
  },
  "type": {
    "definicion": "Campo 'type' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Condition Codes",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_conditions",
    "certeza": "oficial+inferencia_local"
  },
  "name": {
    "definicion": "Campo 'name' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Condition Codes",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_conditions",
    "certeza": "oficial+inferencia_local"
  },
  "asset_class": {
    "definicion": "Campo 'asset_class' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Condition Codes",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_conditions",
    "certeza": "oficial+inferencia_local"
  },
  "sip_mapping": {
    "definicion": "Campo 'sip_mapping' presente en este parquet.",
    "tipo_esperado": "struct<CTA: large_string, UTP: large_string, FINRA_TDDS: large_string>",
    "origen_oficial": "Reference - Condition Codes",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_conditions",
    "certeza": "oficial+inferencia_local"
  },
  "update_rules": {
    "definicion": "Campo 'update_rules' presente en este parquet.",
    "tipo_esperado": "struct<consolidated: struct<updates_high_low: bool, updates_open_close: bool, updates_volume: bool>, market_center: struct<updates_high_low: bool, updates_open_close: bool, updates_volume: bool>>",
    "origen_oficial": "Reference - Condition Codes",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_conditions",
    "certeza": "oficial+inferencia_local"
  },
  "data_types": {
    "definicion": "Campo 'data_types' presente en este parquet.",
    "tipo_esperado": "large_list<element: large_string>",
    "origen_oficial": "Reference - Condition Codes",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_conditions",
    "certeza": "oficial+inferencia_local"
  },
  "legacy": {
    "definicion": "Campo 'legacy' presente en este parquet.",
    "tipo_esperado": "bool",
    "origen_oficial": "Reference - Condition Codes",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_conditions",
    "certeza": "oficial+inferencia_local"
  }
}

**Reference - Exchanges**
- Cat?logo de exchanges.
- local : `C:\TSIS_Data\data\reference\exchanges.parquet`

In [579]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\023_reference_exchanges_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\123_reference_exchanges_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\reference\exchanges.parquet
rows: 51
row_groups: 1
columns: 10

Schema literal:
id: int64
type: large_string
asset_class: large_string
locale: large_string
name: large_string
acronym: large_string
mic: large_string
operating_mic: large_string
participant_id: large_string
url: large_string

Primeras 5 filas literales:

,id,type,asset_class,locale,name,acronym,mic,operating_mic,participant_id,url
0,1,exchange,stocks,us,"NYSE American, LLC",AMEX,XASE,XNYS,A,https://www.nyse.com/markets/nyse-american
1,2,exchange,stocks,us,"Nasdaq OMX BX, Inc.",NaN,XBOS,XNAS,B,https://www.nasdaq.com/solutions/nasdaq-bx-sto...
2,3,exchange,stocks,us,"NYSE National, Inc.",NSX,XCIS,XNYS,C,https://www.nyse.com/markets/nyse-national
3,4,TRF,stocks,us,FINRA Alternative Display Facility,NaN,XADF,FINR,D,https://www.finra.org
4,5,SIP,stocks,us,Unlisted Trading Privileges,NaN,NaN,XNAS,E,https://www.utpplan.com

FILE: C:\TSIS_Data\data\reference\exchanges.parquet
rows: 51
row_groups: 1
columns: 10
reference/exchanges.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "id": {
    "definicion": "Campo 'id' presente en este parquet.",
    "tipo_esperado": "int64",
    "origen_oficial": "Reference - Exchanges",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_exchanges",
    "certeza": "oficial+inferencia_local"
  },
  "type": {
    "definicion": "Campo 'type' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Exchanges",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_exchanges",
    "certeza": "oficial+inferencia_local"
  },
  "asset_class": {
    "definicion": "Campo 'asset_class' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Exchanges",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_exchanges",
    "certeza": "oficial+inferencia_local"
  },
  "locale": {
    "definicion": "Campo 'locale' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Exchanges",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_exchanges",
    "certeza": "oficial+inferencia_local"
  },
  "name": {
    "definicion": "Campo 'name' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Exchanges",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_exchanges",
    "certeza": "oficial+inferencia_local"
  },
  "acronym": {
    "definicion": "Campo 'acronym' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Exchanges",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_exchanges",
    "certeza": "oficial+inferencia_local"
  },
  "mic": {
    "definicion": "Campo 'mic' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Exchanges",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_exchanges",
    "certeza": "oficial+inferencia_local"
  },
  "operating_mic": {
    "definicion": "Campo 'operating_mic' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Exchanges",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_exchanges",
    "certeza": "oficial+inferencia_local"
  },
  "participant_id": {
    "definicion": "Campo 'participant_id' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Exchanges",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_exchanges",
    "certeza": "oficial+inferencia_local"
  },
  "url": {
    "definicion": "Campo 'url' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Exchanges",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_exchanges",
    "certeza": "oficial+inferencia_local"
  }
}

**Reference - Market Status Upcoming**
- Estado/calendario pr?ximo de mercado.
- local : `C:\TSIS_Data\data\reference\market_status_upcoming.parquet`

In [585]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\024_reference_market_status_upcoming_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\124_reference_market_status_upcoming_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\reference\market_status_upcoming.parquet
rows: 24
row_groups: 1
columns: 6

Schema literal:
date: large_string
exchange: large_string
name: large_string
status: large_string
close: large_string
open: large_string

Primeras 5 filas literales:

,date,exchange,name,status,close,open
0,2025-11-27,NASDAQ,Thanksgiving,closed,NaN,NaN
1,2025-11-27,NYSE,Thanksgiving,closed,NaN,NaN
2,2025-11-28,NYSE,Thanksgiving,early-close,2025-11-28T18:00:00.000Z,2025-11-28T14:30:00.000Z
3,2025-11-28,NASDAQ,Thanksgiving,early-close,2025-11-28T18:00:00.000Z,2025-11-28T14:30:00.000Z
4,2025-12-24,NYSE,Christmas,early-close,2025-12-24T18:00:00.000Z,2025-12-24T14:30:00.000Z

Rango date: 2025-11-27 00:00:00 -> 2026-09-07 00:00:00
FILE: C:\TSIS_Data\data\reference\market_status_upcoming.parquet
rows: 24
row_groups: 1
columns: 6
reference/market_status_upcoming.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "date": {
    "definicion": "Fecha asociada al registro.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Market Status",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v1_marketstatus_upcoming",
    "certeza": "oficial+inferencia_local"
  },
  "exchange": {
    "definicion": "Codigo de exchange/venue.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Market Status",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v1_marketstatus_upcoming",
    "certeza": "oficial+inferencia_local"
  },
  "name": {
    "definicion": "Campo 'name' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Market Status",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v1_marketstatus_upcoming",
    "certeza": "oficial+inferencia_local"
  },
  "status": {
    "definicion": "Campo 'status' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Market Status",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v1_marketstatus_upcoming",
    "certeza": "oficial+inferencia_local"
  },
  "close": {
    "definicion": "Precio de cierre de la ventana.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Market Status",
    "mapeo_api": "c",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v1_marketstatus_upcoming",
    "certeza": "oficial+inferencia_local"
  },
  "open": {
    "definicion": "Precio de apertura de la ventana.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Market Status",
    "mapeo_api": "o",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v1_marketstatus_upcoming",
    "certeza": "oficial+inferencia_local"
  }
}

**Reference - Ticker Types**
- Tipolog?as de ticker.
- local : `C:\TSIS_Data\data\reference\ticker_types.parquet`

In [586]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\025_reference_ticker_types_parquet2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\125_reference_ticker_types_attr_table.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

FILE: C:\TSIS_Data\data\reference\ticker_types.parquet
rows: 25
row_groups: 1
columns: 4

Schema literal:
code: large_string
description: large_string
asset_class: large_string
locale: large_string

Primeras 5 filas literales:

      code      description asset_class locale
0       CS     Common Stock      stocks     us
1      PFD  Preferred Stock      stocks     us
2  WARRANT          Warrant      stocks     us
3    RIGHT           Rights      stocks     us
4     BOND   Corporate Bond      stocks     us

FILE: C:\TSIS_Data\data\reference\ticker_types.parquet
rows: 25
row_groups: 1
columns: 4
reference/ticker_types.parquet

Diccionario tecnico de variables (oficial + mapeo local):
{
  "code": {
    "definicion": "Campo 'code' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Ticker Types",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers_types",
    "certeza": "oficial+inferencia_local"
  },
  "description": {
    "definicion": "Campo 'description' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Ticker Types",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers_types",
    "certeza": "oficial+inferencia_local"
  },
  "asset_class": {
    "definicion": "Campo 'asset_class' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Ticker Types",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers_types",
    "certeza": "oficial+inferencia_local"
  },
  "locale": {
    "definicion": "Campo 'locale' presente en este parquet.",
    "tipo_esperado": "large_string",
    "origen_oficial": "Reference - Ticker Types",
    "mapeo_api": "N/A",
    "nota_local": "Documentacion tecnica unificada para certificacion; revisar mapeo fino si aplica.",
    "source_url": "https://polygon.io/docs/stocks/get_v3_reference_tickers_types",
    "certeza": "oficial+inferencia_local"
  }
}

##  detecta en local qué objetivos Polygon clave faltan

**Audit - Polygon Targets Presence**
- Revisi?n de objetivos Polygon presentes/faltantes en local.
- local : `C:\TSIS_Data\data\...`

In [590]:
SCRIPT = Path(r"C:\TSIS_Data\v1\backtest_SmallCaps\notebooks\cell_code\00_data_certification\026_polygon_targets_presence2.py")
exec(SCRIPT.read_text(encoding="utf-8"), globals())

Polygon targets presence audit (max-plan scope, local evidence):

,target,polygon_scope,status_local,paths_found,parquet_count,years_min,years_max
0,Corporate Actions - Dividends,Reference Dividends,MISSING,,NaN,NaN,NaN
1,Day Aggregates (flat files),us_stocks_sip/day_aggs_v1,MISSING,,NaN,NaN,NaN
2,Second Aggregates (API/stream),Stocks aggregates (1-second bars),MISSING,,NaN,NaN,NaN
3,Snapshots (REST),Stocks snapshots endpoints,MISSING,,NaN,NaN,NaN
4,Corporate Actions - Splits,Reference Splits,OK,C:\TSIS_Data\data\additional\corporate_actions...,NaN,NaN,NaN
5,Economic - Inflation,Economic endpoints,OK,C:\TSIS_Data\data\additional\economic\inflatio...,NaN,NaN,NaN
6,Economic - Inflation Expectations,Economic endpoints,OK,C:\TSIS_Data\data\additional\economic\inflatio...,NaN,NaN,NaN
7,Economic - Treasury Yields,Economic endpoints,OK,C:\TSIS_Data\data\additional\economic\treasury...,NaN,NaN,NaN
8,Fundamentals - Balance Sheets,Fundamentals statements,OK,C:\TSIS_Data\data\fundamentals\balance_sheets,-1.0,NaN,NaN
9,Fundamentals - Cash Flow Statements,Fundamentals statements,OK,C:\TSIS_Data\data\fundamentals\cash_flow_state...,-1.0,NaN,NaN
10,Fundamentals - Income Statements,Fundamentals statements,OK,C:\TSIS_Data\data\fundamentals\income_statements,-1.0,NaN,NaN
11,Fundamentals - Ratios,Fundamentals ratios,OK,C:\TSIS_Data\data\fundamentals\smallcap_ratios...,-1.0,NaN,NaN
12,IPOs,Reference IPOs,OK,C:\TSIS_Data\data\additional\ipos\all_ipos.par...,NaN,NaN,NaN
13,Minute Aggregates (flat files),us_stocks_sip/minute_aggs_v1,OK,C:\TSIS_Data\data\ohlcv_intraday_1m,-1.0,2004.0,2025.0
14,News,Stocks News endpoint,OK,C:\TSIS_Data\data\additional\news,-1.0,NaN,NaN
15,Quotes (NBBO tick-level),us_stocks_sip/quotes_v1,OK,C:\TSIS_Data\data\quotes_p95 | C:\TSIS_Data\da...,-1.0,2004.0,2025.0
16,Reference - Condition Codes,Reference endpoints,OK,C:\TSIS_Data\data\reference\condition_codes.pa...,NaN,NaN,NaN
17,Reference - Exchanges,Reference endpoints,OK,C:\TSIS_Data\data\reference\exchanges.parquet,NaN,NaN,NaN
18,Reference - Market Status Upcoming,Reference endpoints,OK,C:\TSIS_Data\data\reference\market_status_upco...,NaN,NaN,NaN
19,Reference - Ticker Events,Ticker Events,OK,C:\TSIS_Data\data\additional\corporate_actions...,NaN,NaN,NaN
20,Reference - Ticker Types,Reference endpoints,OK,C:\TSIS_Data\data\reference\ticker_types.parquet,NaN,NaN,NaN
21,Short Data - Short Interest,Short Interest endpoint,OK,C:\TSIS_Data\data\short_data\short_interest,-1.0,NaN,NaN
22,Short Data - Short Volume,Short Volume endpoint,OK,C:\TSIS_Data\data\short_data\short_volume,-1.0,NaN,NaN
23,Trades (tick-level),us_stocks_sip/trades_v1,OK,C:\TSIS_Data\data\trades_ticks_2004_2018 | C:\...,-1.0,2004.0,2025.0

Missing targets:

                           target                      polygon_scope
0   Corporate Actions - Dividends                Reference Dividends
1     Day Aggregates (flat files)          us_stocks_sip/day_aggs_v1
2  Second Aggregates (API/stream)  Stocks aggregates (1-second bars)
3                Snapshots (REST)         Stocks snapshots endpoints

Diccionario de faltantes (referencia Massive):

,target,que_es,canal,granularidad,historico,doc_massive
0,Corporate Actions - Dividends,"Eventos de dividendos por ticker (cash amount,...",REST (Reference / Corporate Actions),Evento corporativo (no barra temporal).,Depende del plan; util para lifecycle y ajuste...,https://massive.com/docs/rest/stocks/corporate...
1,Day Aggregates (flat files),OHLCV diario por equity US en archivo diario b...,Flat Files S3,1 dia (daily bars).,En Stocks Advanced: all history (segun tabla d...,https://massive.com/docs/flat-files/stocks/day...
2,Second Aggregates (API/stream),Barras OHLCV por segundo en tiempo real para s...,WebSocket,1 segundo.,No flat-file historico dedicado; para historic...,https://massive.com/docs/stocks/ws_stocks_a
3,Snapshots (REST),Snapshot consolidado del mercado/ticker con ul...,REST,Estado instantaneo (point-in-time).,Endpoint de estado actual; no dataset historic...,https://massive.com/docs/rest/stocks/snapshots...

Notes:
- `status_local=OK` valida presencia local, no completitud histórica por ticker.
- `parquet_count=-1` significa timeout/errores en conteo rápido.
- En datasets masivos, este audit prioriza robustez/velocidad sobre conteo exacto exhaustivo.